scylladb/scylla-machine-image

- aws/ami/README.md
- aws/ami/build_ami.sh
also added an option to download non scylla-core rpms,
so people won't need to built those every time
> Clearing up the docs on how to build from with the --localrpm option

- dist/redhat/build_rpm.sh
as part of building the RPM, we'll copy the cloudformation yaml into `/build`
for example:
```
build/CLOUDFORMATION/scylla_cluster_666.development_20200305.02bc4a7.yaml
```
> Versioning of the cloudformation yaml

- Makefile
- README.md
- source/conf.py
- source/index.rst
- source/user_data_v2.rst
* Add it as a sphinx sphinx-jsondomain
> Adding docs for the AMI user-data format v2

- aws/cloudformation/scylla.yaml
- aws/cloudformation/scylla.yaml.j2
Guy.C asked for it, Guy got it
Fixes #31
> feature(cloudformation): add i3.metal to the supported list

- README.md
> Fix the venv command

- aws/ami/build_ami.sh
- dist/redhat/scylla-machine-image.spec
we don't want to have $PRODUCT in the direcotry structure
we want it to be the same across opensource and enterprise
> fix the diretory to not be base on the packge_name

- gce/image/build_image.sh
Today before building gce image, we need to get from repo the relevant packages version, in order to do it we are actually downloading the package although we are not using it
Setting the option to get package version information without downloading the packages
> build_image.sh: get RPM version without downloading packages

- aws/ami/build_ami.sh
- aws/ami/files/99_user_alias.cfg
- aws/ami/files/scylla_install_ami
- aws/ami/scylla.json
This reverts commit de1bb48faf75fc2edbfa83dc9108d69217476a21.
We have problem on Amazon Linux kernel on scylladb/scylla#7607, have to
moving back to CentOS7.
> Revert "aws: switch AMI distribution to Amazon Linux 2"

- aws/ami/README.md
- common/scylla_configure.py
- common/scylla_create_devices
- common/scylla_image_setup
Added support of creating raid and mount to /var/lib/scylla on attached
devices (ebs volumes for aws and nvme* volumes for gce) and instance_store
volumes for aws.
> feature(volumes_support): Support for aws instance ebs or nvme devices

- gce/image/build_image.sh
--localrpm mode is broken, due to calling wrong function name.
Fix to correct one.
> gce: fix --localrpm build

- gce/image/build_deb_image.sh
- gce/image/files/scylla_install_image
- gce/image/scylla_gce.json
Ported Ubuntu AMI code to GCE.
----
Add support Ubuntu 20.04LTS image for GCE.
> gce: support Ubuntu 20.04LTS image

- SCYLLA-VERSION-GEN
> release: prepare for 4.6.dev

- azure/image/Dockerfile_deb
- azure/image/README.md
- azure/image/build_azure_image.sh
- azure/image/build_azure_with_docker.sh
- azure/image/files/scylla_install_azure
- azure/image/scylla_azure.json
- azure/image/variables.json
- common/scylla_create_devices
As we want to be able to support additional cloud provides, we be able creating Scylla machine image on Microsoft Azure platform
As first step, let's build Scylla Azure image with Packer tool
(refernce: https://microsoft.github.io/AzureTipsAndTricks/blog/tip201.html)
Need to get https://github.com/scylladb/scylla/pull/7807 merged before
Fixes: https://github.com/scylladb/scylla-machine-image/issues/54
> Feature: Azure image support

- aws/cloudformation/scylla.yaml
- aws/cloudformation/scylla.yaml.j2
Since the AMI move to Ubuntu, we need to install different the cfn tools
on boot,
IDEA: make it support both repos
> fix(cfn): move to use ubuntu base repo as master does

- aws/cloudformation/scylla.yaml
- aws/cloudformation/scylla.yaml.j2
This commit includes:
- Re-order parameters by using AWS::CloudFormation::Interface
- Add friendly name for parameters
- A few description clarifications
- Change the InstanceCount to be a string with list of 1-10
Fixes: #180 
@yaronkaikov please review.
**The form new design:**
> Cloudformation: reorganize and clarify the form

- .github/workflows/build.yml
> build: use Ubuntu 20.04 to build deb package

- packer/build_deb_image.sh
- packer/scylla_install_image
Updating new gpg key for machine image installation
> fix(build_deb_image.sh): update gpg key

- packer/build_deb_image.sh
- packer/scylla.json
As a preparation for https://github.com/scylladb/scylla-pkg/issues/2616, setting label creation during the actuall image build (for all vendors)
> packer/build_deb_image.sh: align tags

- aws/cloudformation/scylla-aarch64.yaml.j2
This is a preparation for https://github.com/scylladb/scylla-pkg/issues/2616
in order to support AMI promote for arm based arch, we need to generate the cloudformation yaml file based on the relevant instance types
> cfn:Add template to support arm based machines

- .github/workflows/build.yml
- common/scylla_ec2_check
- common/scylla_image_setup
- common/scylla_login
- lib/scylla_cloud.py
- lib/scylla_cloud_io_setup.py
- tests/test_aws_instance.py
Implement aws_instance testcase, and run it on GitHub Actions.
Also fix two bugs on aws_instance found in the testcase.
> tests: add aws_instance testcase

- .github/workflows/build.yml
- tests/test_gcp_instance.py
Implement gcp_instance testcase, and run it on GitHub Actions.
Signed-off-by: Takuya ASADA <syuu@scylladb.com>
> tests: add gcp_instance testcase

- .github/workflows/build.yml
- lib/scylla_cloud.py
- lib/scylla_cloud_io_setup.py
- tests/test_aws_instance.py
- tests/test_azure_instance.py
Implement azure_instance testcase, and run it on GitHub Actions.
Also fixes following azure_instance bug:
- Userdata is not implemented (#319)
- Got abstract method error because of missing instance_size() (#319)
- metadata url is wrong (#321)
- is_unsupported_instance_class() is not implemented, and does not needed (#325) (327)
- missing "Temporary/Resource Disk" support
- fix failing is_azure_instance() (#331)
> tests: add azure_instance testcase

- packer/scylla_install_image
This remove unneeded packages on Ubuntu image, includes:
- Drop snapd and modemmanager
- Purge uninstalled packages
- Run autoremove after uninstalling packages
> ubuntu: drop unneeded packages

- lib/scylla_cloud.py
Backporting Azure patches to branch-5.0.
It incudes following patches:
- [azure_instance: implement user-data](https://github.com/scylladb/scylla-machine-image/commit/37768f6b5d8ad40e26ef86a1db3fe03e56adc668)
- [azure_instance: fix metadata url for location and zone](https://github.com/scylladb/scylla-machine-image/commit/f2745ab01c48d969c6a9dabec4e6a19762c53271)
- [azure_instance: remove unneeded is_unsupported_instance_class()](https://github.com/scylladb/scylla-machine-image/commit/5b53ee3922f2f992d5f80d010a8b1cad6055e4b0)
- [azure_instance: fix bromen is_recommended_instance_size()](https://github.com/scylladb/scylla-machine-image/commit/c7b90846532ea484ceeaa581fb773d2935c31ce2)
- [azure_instance: support "swap disk"](https://github.com/scylladb/scylla-machine-image/commit/5d2c3eef957b …
> Azure patches for branch-5.0

- packer/build_deb_image.sh
- packer/scylla.json
Following https://github.com/scylladb/scylla-machine-image/pull/383. renaming `version` parameter to `scylla_version` parameter
> [AMI/GCP/Azure] - Align images name - follow up

- lib/scylla_cloud.py
Adding support Lasv3-series.
Closes https://github.com/scylladb/scylla-machine-image/issues/420
> azure_instance: add support Lasv3-series

- packer/scylla_install_image
for debugging purposes
Fixes: https://github.com/scylladb/scylla-machine-image/issues/497
> [images] Adding vim.tiny editor

- packer/apply_cis_rules
- packer/scylla.json
Related to https://github.com/scylladb/scylla-enterprise/issues/4967
We need to apply the following:
https://github.com/scylladb/scylla-enterprise-machine-image/pull/72
https://github.com/scylladb/scylla-enterprise-machine-image/pull/73
https://github.com/scylladb/scylla-enterprise-machine-image/pull/74
https://github.com/scylladb/scylla-enterprise-machine-image/pull/76
Closes scylladb/scylla-enterprise-machine-image#78
> Sync enterprise to OSS

- SCYLLA-VERSION-GEN
Following the license changes in f3eade2f6249ef4a964f34da76ec75aaacec26ff
> Update version to: 2025.1.0-dev

- packer/scylla_install_image
Adding tools needed by the cloud team
Fixes: https://github.com/scylladb/scylla-machine-image/issues/618
> [images] add devops tooling to our images

- renovate.json
limiting the renovate to run every weekend, to reduce the number of updates
> renovate: run every weekend

- packer/apply_cis_rules
We need to set correct owner and permission on User Initialization Files.
> CIS compliance: set correct owner & permission on User Initialization Files
