dist/redhat/build_rpm.sh

Since in scylla-pkg this test phase was questioned
https://github.com/scylladb/scylla-pkg/pull/721#pullrequestreview-357376537
I think we are better off with having it here during the rpm build

Run the unittest before building the RPM

---

dist/redhat/build_rpm.sh

since unit test running move into build_rpm.sh, those were missing.

Add python3-devel and python3-pip to build_rpm.sh

---

dist/redhat/build_rpm.sh
dist/redhat/scylla-machine-image.spec.mustache

To support both CentOS 7 and CentOS 8 with the same RPM, remove
distribution information from the "Release" string in the RPM spec file.
Similar fix was already done in scylla.git in commit:
scylladb/scylla@ef88e1e
Ref: scylladb/scylla#5631.

dist/redhat: Make RPM release independent of distribution

---

aws/ami/scylla.json

If `user_data_format_version` as missing scylla-cluter-tests fails to use
those AMIs with the correct user-data

Add user_data_format_version tag to AMI on creation

---

aws/scylla_configure.py

The AMI was setting auto_bootstrap to false, allowing it to be
overriden via user-metadata.
Unofourtunatly, users don't follow guidlines - and we are changing the
default to be true (and allowing it to be overriden to false) if needed
Fixes: #25

Change the default of auto_bootstrap to be True

---

dist/redhat/build_rpm.sh
dist/redhat/scylla-machine-image.spec

The package names for enterprise are "scylla-enterprise" and
"scylla-enterprise-python3". Let's fix the hard-coded open source
package names in spec file dependencies list.
Reported-by: Yaron Kaikov <yaronkaikov@scylladb.com>

dist/redhat: Fix Scylla and Python dependencies

---

aws/scylla_login

We had rename the scylla-ami-setup to scylla-image-setup.
But the old name is still used in aws scylla_login script.
Error:
```
Traceback (most recent call last):
File "/opt/scylladb/scylla-machine-image/libexec/scylla_login", line 115, in <module>
setup = systemd_unit('scylla-ami-setup.service')
File "/opt/scylladb/scripts/scylla_util.py", line 619, in __init__
raise SystemdException('unit {} not found'.format(unit))
scylla_util.SystemdException: unit scylla-ami-setup.service not found
```
/CC @fruch @bentsi

aws/scylla_login: update rest scylla-ami-setup to new name

---

dist/redhat/scylla-machine-image.spec

Seem like we forgot this part, and now when upgrading AMIs from version < 4.0
We run into upgrade error:
```
--> Finished Dependency Resolution
Error: Package: scylla-ami-3.3.4-20200616.0ae14e01506.noarch (@/scylla-ami.noarch)
Requires: scylla = 3.3.4
Removing: scylla-3.3.4-0.20200616.ec12331f116.x86_64 (@/scylla.x86_64)
scylla = 3.3.4-0.20200616.ec12331f116
Updated By: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64 (scylla-4.0)
scylla = 4.0.3-0.20200621.1fcf38abd9b
Available: scylla-4.0.rc0-0.20200325.78f5afec30.x86_64 (scylla-4.0)
scylla = 4.0.rc0-0.20200325.78f5afec30
Available: scylla-4.0.rc1-0.20200406.9908f009a4a.x86_64 (scylla-4.0)
scylla = 4.0.rc1-0.20200406.9908f009a4a
Available: scylla-4.0.rc2-0.20200421.89e79023aeb.x86_64 (scylla-4.0)
scylla = 4.0.rc2-0.20200421.89e79023aeb …
```

Adding `Obsoletes: scylla-ami` for inplace upgrades of AMIs

---

aws/ami/build_ami.sh
aws/ami/files/99_user_alias.cfg
aws/ami/files/scylla_install_ami
aws/ami/scylla.json

On Amazon Linux 2, we can get more recent version kernel by default,
with EC2 device driver support.
This commit changes following things:
- dropped AMI variable to specify source AMI, introduced source_ami_filter
to automatically lookup latest Amazon Linux 2 AMI insteead.
- AMI default user changes:
- changed default user as "scyllaadm"
- make "centos" user as an alias of "scyllaadm"
- deleted "ec2-user" user which is default user on Amazon Linux 2
- dropped kernel-ml installation code and udev/bootparam customize for
EC2 support, and also initramfs generation for EC2 support. Since
Amazon Linux 2 is optimized for EC2, we don't need these customize.
- reuired small changes to make scripts compatible with Amazon Linux 2:
- build time default user changed to ec2-user
- cloud.cfg: …

aws: switch AMI distribution to Amazon Linux 2

---

aws/ami/scylla.json
aws/scylla_image_setup

This PR enable swap in scylla_image_setup, it will be enabled during AMI instance init.
The swap is always helpful, and recommended for scylla user. We don't need to make it configurable, and just enable it all the time.
Current default root disk size (10G) might be not enough if the instance type is very large. Let's increase it to 30G.
/CC @roydahan @tzach @bentsi @fruch

scylla_image_setup: enable swap during AMI instance init

---

aws/ami/build_ami.sh

Recently (24-25/Sep), our images started missing ENA support.
seem like out base image was very old moving to
"CentOS Linux 7 x86_64 HVM EBS ENA 1905" (ami-0e4bba886a574c2d8) 
has fixed the issue.
Fixes: scylladb/scylla#7295

fix(ena_support): move to newer centos base image

---

gce/image/build_image.sh

in case we want to re-build gce image , it will fail by default. Adding -force flag to override it
This change required by https://github.com/scylladb/scylla-pkg/pull/1624

Force gce image build when already exists

---

aws/ami/build_ami.sh

Today before building AMI image, we need to get from repo the relevant packages version,
In order to do it we are actually downloading the package although we are not using it
Setting the option to get package version information without downloading the packages
based on fix commit https://github.com/scylladb/scylla-machine-image/commit/56e94c5252e6da37928c329c1b0a9e95b22e853b

build_ami.sh: get RPM version without downloading packages

---

aws/ami/build_ami.sh
gce/image/build_image.sh

An issue was raised by Takuya in https://github.com/scylladb/scylla/issues/7465
upon release when you run get_version_from_remote_rpm, you get an output for all releases instead off the latest one only
Fixing it here

get_version_from_remote_rpm: get latest version on release

---

aws/scylla_create_devices
k8s/Dockerfile
k8s/build_image.sh
k8s/scylla_k8s_node_setup

This script allows to configure k8s node disks and tune networking. 
Priviledged pods should run it as a entrypoint, and provide two environmental variables:
* ROOT_DISK - where Scylla root directory should be mounted
* ROOT_MOUNTPOINT - path to directory where host filesystem is mounted

k8s: Added script for setting up k8s nodes

---

gce/image/files/scylla_install_image

scylla_swap_setup runs as part of scylla_setup during first boot of the instance that is created from the image

fix(gce image): do not setup swap when creating an image

---

gce/image/build_image.sh
gce/image/scylla_gce.json

Today the GCE image name is based on product=scylla and rpm version.
When we are building GCE image more then once based on the same rpm version the image is overriding and deleted
Setting a unique image name so we can keep the history of images
Backport to 4.3 is needed

GCE image:Set a uniuqe image name

---

common/scylla_image_setup
common/scylla_login

Since 3fefa52, we dropped scylla_util.run() and scylla_util.out(), we need to
use subprocess.run() instead.
Related scylladb/scylla#7667
Fixes: scylladb/scylla/issues#7695

switch to subprocess.run()

---

aws/ami/files/scylla_install_ami

Since we moved to kernel-ml, we stopped using scylla-ixgbevf/scylla-ena
because kernel-ml contains updated drivers.
So we don't need to install NIC driver repo, also don't need development
packages to build kernel module.

aws: drop NIC driver repo and kernel development packages

---

aws/ami/build_ami.sh
aws/ami/files/scylla_install_ami
dist/redhat/build_rpm.sh

Currently we don't provide aarch64 rpm on our official repo, but it can
build locally by standard procedure of building package, on aarch64 machine.
Let's support the architecture on scylla-machine-image too, for testing purposes.
Related: scylladb/scylla#7026

aws: support building aarch64 AMI

---

aws/ami/build_ami.sh
gce/image/build_image.sh

Today we have PRODUCT definition in SCYLLA-VERSION-GEN , let's start
using it as a source instead of defining it manually for both AMI and
GCE. This way we can have a generic code for both open source and
enterprise

Set product for AMI and GCE based on SCYLLA-VERSION-GEN

---

common/scylla_create_devices

method from scylla_util for gce instance return only name
of empherial device. Fix method to get_default_devices full path
for gce instances
Fix issue: https://github.com/scylladb/scylla-machine-image/issues/91

fix(gce_device_path): fix get full device path for gce image

---

gce/image/build_image.sh
gce/image/files/scylla_install_image

When building GCE image in enterprise the build pass although we getting en error as mention below:
7:31:42  [0;32m    googlecompute: Scylla for Centos 8 - x86_64                     34 kB/s |  19 kB     00:00[0m
17:31:42  [0;32m    googlecompute: Scylla for centos 8                             8.8 kB/s | 3.8 kB     00:00[0m
17:31:43  [0;32m    googlecompute: No match for argument: scylla-python3[0m
17:31:43  [0;32m    googlecompute: No match for argument: scylla-machine-image[0m
17:31:43  [0;32m    googlecompute: No match for argument: scylla-debuginfo[0m
(referance https://jenkins.scylladb.com/job/enterprise-2021.1/job/gce-image/7/consoleFull)
Let's start installing scylla in GCE image based on product , so it will
work for both open source and enterprise

scylla_install_image:install based on product

---

aws/ami/files/scylla_install_ami

Instead of hardcoding clocksource=tsc on bootparameter, we need to configure
it ondemand, since we have different types of hypervisor which required
different clocksource to optimize.
To do so, we need to run perftune.py tune-clock mode to auto-configure clocksource.
Related scylladb/scylla#7444

Enable clocksource setting on AMI

---

aws/ami/Dockerfile
aws/ami/build_with_docker.sh

build_with_docker.sh currently fails to call ../../SCYLLA-VERSION-GEN,
fixed the issue to make it runnable again.

aws/ami: fix broken Docker build for CentOS AMI

---

common/scylla_configure.py
common/scylla_create_devices

scylla_create_devices support 3 variants for data_device:
- auto: for aws instance will search nvme(ephemeral) device,
if not found will search ebs volumes(ebs).
for gce instances will search nvme(attached) devices
for aws instances:
- attached: will search ebs volumes(attached) and if such volumes
added to os as nvme devices, will use them
- instance_store: will search nvme(ephemeral) devices and use

fix(scylla_create_devices): improve logic for found devices

---

aws/ami/build_deb_ami.sh

As done on #102 for the CentOS based AMI - 
Enable this option on ubuntu based AMI too.

AMI Build image for unified-deb: Add dry-run mode

---

dist/debian/debian_files_gen.py

Ported https://github.com/scylladb/scylla/commit/d7f202f9008ce312a8d0b71b41d073db7923ce1c to scylla-machine-image to fix scylladb/scylla-enterprise-machine-image#16.
----
Current renaming rule of debian/scylla-* files is buggy, it fails to
install some .service files when custom product name specified.
Introduce regex based rewriting instead of adhoc renaming, and fixed
wrong renaming rule.
Fixes scylladb/scylla-enterprise-machine-image#16

dist/debian: fix renaming debian/scylla-* files rule

---

common/scylla_create_devices
common/scylla_image_setup

When we run AMI without ephemeral disks, scylla-image-setup.service will
fail with python traceback.
It is not user friendly, it's better to print human readable message.
Fixes #111
Fixes #112

Stop traceback when no ephemeral disks attached, print human readable message

---

dist/debian/build_deb.sh

We recently started to build deb package in scylla-machine-image but
package version is X.X.X while spinning RCs we need to change the
version format to X.X~rcX
When tried to build unified-deb in 4.5 (rc0) we saw the following error:
```
13:19:41  This package has a Debian revision number but there does not seem to be
13:19:41  an appropriate original tar file or .orig directory in the parent directory;
13:19:41  (expected one of scylla-machine-image_4.5~rc0-20210405.0ef5d340d7f.orig.tar.gz, scylla-machine-image_4.5~rc0-20210405.0ef5d340d7f.orig.tar.bz2,
13:19:41  scylla-machine-image_4.5~rc0-20210405.0ef5d340d7f.orig.tar.lzma,  scylla-machine-image_4.5~rc0-20210405.0ef5d340d7f.orig.tar.xz or scylla-machine-image.orig)
13:19:41  continue anyway? (y/n) Use of uninitialized value $ans in …
```

dist/debian/build_deb.sh:debian version number fix

---

aws/ami/files/scylla_install_ami

Currently, 'centos' user is alias of 'scyllaadm', and its home directory
is /home/scyllaaadm, but original /home/centos is still remain.
To maximize compatibility, drop /home/centos and make it symlink of
/home/scyllaadm.
Fixes #120

aws/ami: drop /home/centos, make it symlink of /home/scyllaadm

---

gce/image/build_deb_image.sh
gce/image/build_image.sh

This is done together with https://github.com/scylladb/scylla-pkg/pull/1997
I want the GCE pipeline to get an error when GCE creation failed.
We also run the process with tee to log file, so we can read the ID from it.
This is a duplication, as the build_image script already writes a log.
- Get the name of the log from caller (still supply the current value as default). This will prevent the need to save a copy of the log (tee on tee).
- Search the log for error, and return status.

GCE: Let script return an error

---

dist/debian/debian_files_gen.py

Ubuntu based AMI in enterprise failed due to:
```
16:40:23  [1;31m==> amazon-ebs: Failed to enable unit: Unit file scylla-image-setup.service does not exist.[0m
```
Let's make sure scylla-image-setup.service is constant and not product
based
Fixes: https://github.com/scylladb/scylla-enterprise/issues/1726

dist/debian: Fix scylla-image-setup.service rename

---

aws/ami/files/scylla_install_ami
dist/debian/debian/conffiles
dist/debian/debian/rules
dist/debian/debian/scylla-machine-image.install
dist/redhat/scylla-machine-image.spec

We have permission issue on /home/scyllaadm/, it owned by root:root but
should be scyllaadm:scyllaadm.
However, we create scyllaadm user AFTER installing scylla-machine-image
package, so it's not possible to do that in the package.
We don't really need to keep /home/scyllaadm/.bash_profile in package.
We just need to do "echo /opt/scylladb/scylla-machine-image/scylla_login >> ~/.bash_profile" in scylla_install_ami instead.
In fact, we already do so in GCE since login user of GCE is not static,
we addd scylla_login to /etc/skel/.bash_profile.
So let's align the way to configure .bash_profile to GCE, drop
.bash_profile from rpm/deb packages, configure .bash_profile in
scylla_install_ami.
Also, we need to take care upgrade scylla-machine-image package.
To do so, remove …

dist: remove .bash_profile from package, configure it in scylla_install_ami

---

gce/image/files/scylla_install_image

As outlined in scylladb/scylla#7341, we need to disable writeback cache
on GCE for better performance.

gce: Disable writeback cache

---

aws/ami/files/scylla_install_ami

Just like user alias, add group alias to centos/ubuntu.
Fixes #123

aws: add group alias to centos/ubuntu

---

aws/ami/build_ami.sh
aws/ami/build_deb_ami.sh

The AMI side of #110 
This is done together with scylladb/scylla-pkg#2078
I want the AMI pipeline to get an error when AMI creation failed.
We also run the process with tee to log file, so we can read the ID from it.
This is a duplication, as the AMI script already write logs.
Get the name of the log from caller (still supply the current value as default). This will prevent the need to save a copy of the log (tee on tee).
Search the log for error, and return status.
Also align these scripts to the GCE scripts.

Fail ami in script

---

common/scylla_login

Scylla AMI requires additional disks to construct data volume, so our
AMI image automatically attaches ephemeral disks for it.
However, some unsupported additional instance types does not supported
any additional disks, so AMI will launch without any additional disks.
On such environment, we have added readable error message on 37ec32c,
but it still only able to check on journalctl.
To warn users more clearly, add new warning message on login prompt.
Fixes scylladb/scylla#8501

scylla_login: print warning message when no RAID disks available

---

aws/ami/files/scylla_install_ami

dot files should be owned by user, so chown them.
Fixes #125

aws: chown skel files to scyllaadm:scyllaadm

---

aws/ami/scylla.json

Drop /root/.ssh/authorized_keys entry for Packer temporary SSH key,
since we never need it.
Fixes #133

aws: clear /root/.ssh/authorized_keys entry for Packer temporary SSH key

---

gce/image/build_deb_image.sh
gce/image/build_image.sh
gce/image/scylla_gce.json

got the following error during gce-image build:
```
03:09:46  --> googlecompute: Error creating instance: googleapi: Error 409: The resource 'projects/scylla-images/zones/europe-west1-b/instances/scylla-4-6-dev-0-20210521-a2379b96b1-1' already exists, alreadyExists
```
This is since we are building from same package version and the image
name is not unique.
Let's make sure each gce image buid has a unique name
Fixes: 	https://github.com/scylladb/scylla-pkg/issues/1879

gce-image: set uniqu image name

---

aws/ami/files/scylla_install_ami

We need to create /home/centos symlink on Ubuntu AMI, since we have
centos alias user for compatibility.
Fixes scylladb/scylla-enterprise-machine-image#22

aws: create symlinks for /home/centos on Ubuntu AMI

---

aws/ami/files/scylla_install_ami
aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Install aws-cfn-bootstrap on AMI building time, instead of after instance
launched.
Fixes #150

aws: install aws-cfn-bootstrap on AMI building time

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Today we set ipProtocol to -1 which allow inbound traffic of all types.
Let's specify it to tcp
based on 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
Fixes: https://github.com/scylladb/scylla-machine-image/issues/154

cloudformation:security groups ingress, set to tcp

---

common/scylla_login

MSG_UNSUPPORTED_INSTANCE_TYPE_NO_DISKS is not applied format parameter,
even it passed with '%'.

scylla_login: fix message to apply format parameter

---

aws/ami/build_deb_ami.sh
aws/ami/variables.json.example

Today we have an AMI based on x86 arch only. Now that we have ARM based
packaging , we want to have also AMI based on ARM
Fixes: #137

AMI: Add support for ARM based AMI build

---

aws/ami/build_deb_ami.sh

In https://github.com/scylladb/scylla-machine-image/pull/153/commits/27223c6e7eb5ffb93fb5f535f299bafd17174ac3 we started to support AMI build based on ARM.
I missed a condition typo which broke the x86 based AMI build
Fixing it here

build_deb_ami.sh: Fix condition typo casuing ami build to fail

---

aws/ami/files/scylla_install_ami

We don't want to enable auto update features on our ami, remove
unattended-upgrades and update-notifier-common to disable them.
fixes #152

aws: on Ubuntu AMI, remove auto update features by default

---

aws/ami/build_deb_ami.sh

This is a follow-up fix to https://github.com/scylladb/scylla-machine-image/pull/167.
Let's explicitly check for aarch64 amd x86 and inform incase we have unsupported architecture

build_deb_ami: improve arch verification

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Missing egress rule in security group means CloudFormation will 
automatically add an outbound rule to allow all traffic outbound. Make 
this explicit by adding egress rule if it is the desired configuration. 
No need to parametize it.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#aws-properties-ec2-security-group--examples--Remove_Default_Rule
Fixes: https://github.com/scylladb/scylla-machine-image/issues/161

cloudformation: SGCluster : Missing egress rule

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Missing egress rule in security group means CloudFormation will
automatically add an outbound rule to allow all traffic outbound. Make
this explicit by adding egress rule if it is the desired configuration.
No need to parametize it.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#aws-properties-ec2-security-group--examples--Remove_Default_Rule
Fixes: https://github.com/scylladb/scylla-machine-image/issues/173

cloudformation: SGUser: Add missing egress rule

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Missing egress rule in security group means CloudFormation will
automatically add an outbound rule to allow all traffic outbound. Make
this explicit by adding egress rule if it is the desired configuration.
No need to parametize it.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#aws-properties-ec2-security-group--examples--Remove_Default_Rule
Fixes: https://github.com/scylladb/scylla-machine-image/issues/174

cloudformation: SGAdmin: Add missing egress rule

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Security Groups found with CIDR open to world on ingress. Today it is opened to all IPs allowing only SSH access.
Let's give the customer more control and allow him to specifiy the IP or
rane for public access
Fixes: https://github.com/scylladb/scylla-machine-image/issues/172

cloudformation:SGAdmin:define public access source

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Following a (customer) request, the VPC CIDR should be adjustable,
Due to CFN syntax limitation (no math-operator) the node IPs are
hardcoded (10, 11, etc.) which means CIDR netmask must be one of 8,16,24
Fixes #157

cloudformation: allow custom VPC-CIDR for scylla cluster

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

In https://github.com/scylladb/scylla-machine-image/pull/147 i have  added a parameter for enabling public ip mapping.
Part of the added code, seems to be not relevant 
Removing it

cloudformation: public ip mapping code cleanup

---

gce/image/files/scylla_install_image

We don't want to enable auto update features on our ami, remove
unattended-upgrades and update-notifier-common to disable them.
fixes #171

gce: on Ubuntu AMI, remove auto update features by default

---

gce/image/scylla_gce.json

On GCE, instance name must be unique. However, "scylla-{{user `scylla_version`| clean_resource_name}}" can be conflict, because we may build multiple images from single Scylla version.
We should use unique instance name, and default value of instance_name is unique since it uses uuid (packer-{{uuid}}).
So let's drop the variable from scylla_gce.json, just apply default value.
Note that this is not about image name, it is temporary instance name for packer.
Fixes #184

gce: use unique instance_name

---

aws/ami/Dockerfile
aws/ami/Dockerfile_deb
azure/image/Dockerfile_deb

Packer now has official .rpm/.deb package, let's switch to it and use
up-to-date version to build our EC2/GCE/Azure images.

On Docker image, make packer always up-to-date

---

aws/ami/build_ami.sh
aws/ami/build_deb_ami.sh
azure/image/build_azure_image.sh
gce/image/build_deb_image.sh
gce/image/build_image.sh

-force -on-error=abort means keep alive packer instance when building
failed, it's good feature to debug images, but if we do that by default
we may leave multiple instances unexpectedly, especially with Jenkins.
It should safer to build images without these options.
Related #184

drop "-force -on-error=abort" option from packer build

---

gce/image/scylla_gce.json

Just like we do on Ubuntu 20.04 image, we need to create symlink for
/usr/bin/python on CentOS8 image.
Fixes #191

gce: add /usr/bin/python link update for CentOS8 image

---

packer/scylla_install_image

Seems like we mistakenly added non-standard modules on scylla_install_image at 8915e3e.
Since the script is written for installing packages, the script itself should not have additional dependencies except python interpreter.
Fixes #192
Signed-off-by: Takuya ASADA <syuu@scylladb.com>

scylla_install_image: drop pyyaml dependency

---

aws/cloudformation/scylla.yaml.j2

Today setting a new stack reuqired the user to enter the relevant AMI id depend on the region
Let's add an entry in the map for every region where your product should be available
Fixes: https://github.com/scylladb/scylla-machine-image/issues/159

cloudformation: add ami map per available region

---

aws/ami/build_ami.sh
aws/ami/build_deb_ami.sh
azure/image/build_azure_image.sh
gce/image/build_deb_image.sh
gce/image/build_image.sh
packer/build_deb_image.sh
packer/build_image.sh

Support run build_image.sh/build_deb_image.sh directly by --target <cloud> option.
The script currently located subdirectory of packer to adjust directory
depth of each cloud directories, but it's inconvenient to call longer
path.
So move the script to packer directory, and detect executed via symlink
or not.
To keep compatibility with existing build, direct run will be chdir to
target cloud directory, to use files/ and variables.json for the target.
Fixes #197

support run build_image.sh/build_deb_image.sh directly

---

common/scylla_image_setup
packer/scylla_install_image

Currently, CPU scaling setup is mistakenly running in AMI building time.
This is not correct because the AMI image can run other instance type.
To fix this issue, disable CPU scaling setup on scylla_image_setup, and
add it to scylla_install_image.
Fixes scylladb/scylla#9273

move CPU scaling setup from scylla_image_setup to scylla_install_image

---

aws/ami/files/elrepo-archive.repo
packer/scylla_install_image

After kernel-ml-5.14.0-1, CentOS7 AMI does not boot up, looks like some failure happens on dracut but not able to fix at least for now.
As a workaround fix, pin down kernel version to 5.13.13-1 until boot
failure fixed.
Fixes #196

Workaround for boot failure on kernel-ml 5.14.x

---

common/scylla_image_setup

We found that scylla_cpuscaling_setup won't execute until RAID
construction finished, and it may take few minites or more on larger
systems.
To minimize initialization time, configure CPU scaling first, then
execute rest of setup.

scylla_image_setup: run scylla_cpuscaling_setup earlier

---

aws/ami/files/elrepo-archive.repo
packer/scylla_install_image

Seem like kernel-ml 5.14.1 boot up issue was caused because xen-blkfront
is not installed on its initramfs, we need to re-generate it with the
driver.
Revert the workaround since we found a solution.

Revert workaround of kernel-ml boot up issue, fix the problem

---

aws/ami/scylla.json
azure/image/scylla.json
gce/image/scylla.json
packer/build_deb_image.sh

Following scylladb/scylla-pkg#2393, All image builds (official or debug) have the same image name prefix.
Let's make sure when we (releng) building an image (ami,gce or azure) we create the name of the image with a general debug prefix
Once this will be merge, we need also to change hydra.sh script in SCT repo to fetch the latests AMI images and ignore debug ami images prefix (scylladb/scylla-cluster-tests#3950)

build_deb_image.sh:add debug option for testing

---

aws/ami/files/scylla_install_ami

Seem like kernel-ml 5.14.1 boot up issue was caused because xen-blkfront
is not installed on its initramfs, we need to re-generate it with the
driver.
See #196

aws: add xen-blkfront driver to kernel-ml initramfs

---

aws/ami/files/scylla_install_ami

Seem like kernel-ml 5.14.1 boot up issue was caused because xen-blkfront
is not installed on its initramfs, we need to re-generate it with the
driver.
See #196

aws: add xen-blkfront driver to kernel-ml initramfs for 4.3

---

common/scylla_image_setup
packer/scylla_install_image

It is bad to install packages on instance startup time, we want to
finish installing on AMI building time.
For CentOS AMI, install cpupower on AMI building time.
For Ubuntu AMI, install cpufrequtils and configure it on AMI building
time.
Fixes #204
----
**This requires https://github.com/scylladb/scylla/pull/9326 to merge, otherwise fails to build.**

Preinstall cpupower/cpufrequtils on AMI building time

---

aws/cloudformation/scylla.yaml.j2

Default value 0.0.0.0/0. This open the Ingress to the world by default.
Let's delete the default value and let the customer define it
Fixes: https://github.com/scylladb/scylla-machine-image/issues/210

Cloudformation: remove default ingress route

---

aws/cloudformation/scylla.yaml.j2

We don't allow ipv6 on AWS::EC2::VPC so it doesn't affect and relevant
to anything. in addition we don't want to add this option since it's not
common and will complex the flow.
Fixes #211

cloudformation: remove ipv6 from ingress security group

---

packer/build_image.sh

PR #203 added the `--debug` option to the `build_deb_image.sh` (ubutnu-based) for
testing purpose. This PR adds the same option but to the `build_image.sh` (centos-based).

ami: add debug option for build ami centos-based

---

aws/cloudformation/scylla.yaml
aws/cloudformation/scylla.yaml.j2

Currently SGCluster is open inside for all protocols and ports. This
security group is being used by Scylla internal cluster communication,
let's make sure we only enable relevant tcp ports based on https://docs.scylladb.com/operating-scylla/admin/#id6
Fixes: https://github.com/scylladb/scylla-machine-image/issues/213

SGCluster:set ingress rules to match Scylla ports

---

aws/ami/files/scylla_install_ami
common/scylla_image_setup
gce/image/files/scylla_install_image

It is bad to install packages on instance startup time, we want to
finish installing on AMI building time.
For CentOS AMI, install cpupower on AMI building time.
For Ubuntu AMI, install cpufrequtils and configure it on AMI building
time.
Fixes #204

Preinstall cpupower/cpufrequtils on AMI building time for branch-4.4

---

common/scylla_create_devices

Just like EBS disks for EC2, we want to use persistent disk on GCE.
We won't recommend to use it, but still need to support it.
Fixes #215
----
Requires https://github.com/scylladb/scylla/pull/9395 to merge

scylla_create_devices: add persistent disk support for GCE

---

aws/cloudformation/scylla.yaml.j2

In addition to the unused condition mentioned on the description, I
removed the `scylla.yaml` file since we have no reason to keep useless file
that in any case needs re-generate + AMI-ID inject before any use.

cloudformation: remove unused if condition and the scylla.yaml file

---

packer/scylla.json
packer/scylla_install_image

To fullfill SOC2 requirement, we need to make sure OS is up to date.
However, just running 'yum update' on whole cluster nodes may install
different versions of packages, that can cause issue on Scylla.
So generate package manifest that records package versions of all
required packages for Scylla, and use the manifest for Scylla upgrade.
Package manifest build while generating AMI, download to
build/scylla-packages.txt on build host.
Related with https://github.com/scylladb/scylla-pkg/issues/1869

aws: add support package manifest file

---

packer/build_deb_image.sh

The ubuntu package name contains `~` which cause image-build to fail,
In this commit, the package-version rename with `.` instead of `~`

azure-image: rename ubuntu package during image-build

---

packer/build_deb_image.sh

during Azure image build in 4.6 we got the following error
```
15:45:50  1 error(s) occurred:
15:45:50
15:45:50  * The setting managed_image_name must match the regular expression
15:45:50  "^[^_\\W][\\w-._)]{0,79}$", and not end with a '-' or '.'.
```
This is due to the use of `~` char when we spin a release candidate
Fixing it

Azure:set image name to match azure rules

---

packer/build_image.sh

`repo-for-install` in print_usage() causes "command not found" error,
this should be typo of single quote.
So replace ` to '.
Fixes #249

build_image.sh: fix typo on print_usage()

---

common/scylla_image_setup

On AWS, "supported" instance type means it should have ephemeral disks.
So scylla_image_setup checks instance type before running io_setup like
this:
if cloud_instance.is_supported_instance_class():
cloud_instance.io_setup()
But this is not enough for GCE, it can configure instance without
ephemeral disks even instance type is 'supported' one.
To support such case, we also need to check the instance has ephemeral disks.
Fixes #243
Signed-off-by: Takuya ASADA <syuu@scylladb.com>

scylla_image_setup: add check current instance has ephemeral disks

---

packer/build_deb_image.sh

The version-replace line was set specifically for Azure. this commit
fix it that will replace all image-versions.
Ref #121
@yaronkaikov please review and merge.

packer: fix version-replace line

---

common/scylla_image_setup

We should check nr_disks > 0, not nr_disks < 0.

scylla_image_setup: bug fix to check ephemeral disks count

---

packer/scylla.json

This reverts commit d49709f4318a4a6cee94b0540c8c5561d9b9d0fa.
Still we cannot find root cause of the problem, but we found that the
issue does not reproduced on latest scylla / packer / ubuntu image.
So we can revert the workaround now.

Revert "GCE: workaround for login issue on Ubuntu image"

---

packer/build_deb_image.sh
packer/build_image.sh

In the current scripts, if product is not given, even though it
is defaulted to whatever is in `build/SCYLLA-PRODUCT-FILE`, it
will not propagate to the packer vars (through `--install-args`).
This is a problem if the default is different than the one set in
`packer/scylla_install_image`.
This change will make the default always propagate to the packer
whether it is the default or a user set value.

Build ami scripts: Make default product really take effect

---

common/scylla_create_devices
common/scylla_image_setup
common/scylla_login

We currently not able to run scylla on root disk only environment, even
with development mode.
Because we specified "RequiredBy=scylla-server.service" on
scylla-image-setup.service, and scylla-image-setup.service fails when
additional disks not found.
To fix this, we need to finish scylla_image_setup even additional disks
not detected, it should fails at scylla-server.service instead (same as
EBS mode).
Fixes #256

Make root disk only environment usable in development mode

---

packer/build_deb_image.sh

To use latest EC2 instance type, we need to update source AMI to latest
one.
This is needed for https://github.com/scylladb/scylla/pull/9730
to run AMI in new instance type.

build_deb_image.sh: Update to latest Ubuntu 20.04LTS AMI

---

common/scylla_login

This pull request fixes a few minor problems in `scylla_login`:
1. Changing spelling from ScyllaDB (the company) to Scylla (the database) in all places the database (not company) was mentioned.
2. Replacing tabs with spaces in `MSG_HEADER` (spaces and tabs were mixed and an incorrect number of spaces was used).
3. A few style, grammatical, formatting fixes to make the messages more clear.
4. Adding missing `sudo` in a few command tips.
5. Removed places where "EC2" was hardcoded as now there are images for Scylla on GCE. A hardcoded "Getting started Amazon" is replaced with `cloud_instance.GETTING_STARTED_URL` (which was already there, but was not used). Note that those `cloud_instance.GETTING_STARTED_URL` links are incorrect (see issue https://github.com/scylladb/scylla/issues/9043), but …

scylla_login: Minor style, formatting fixes

---

packer/build_deb_image.sh
packer/build_image.sh
packer/scylla.json

The AMI builder of the packer can copy the newly created AMI as
part of the normal flow. This has the advantage of copying the
image along with the Tags and Permissions set without having to
have a dedicated script for doing so.
Here we add an optional `--ami-regions` parameter that takes a
comma separated list of regions and copy the AMI once it's build
has succeeded.
Signed-off-by: Eliran Sinvani <eliransin@scylladb.com>

AWS AMI: add `ami-regions` parameter control

---

common/scylla_login

This fixes "AttributeError: 'gcp_instance' object has no attribute 'non_root_disks'" error on GCP, and also same error on Azure.
Fixes #259

scylla_login: support getting available data disks for GCP and Azure

---

packer/scylla.json

Since we configure almost same settings on all IaaS images, we should
use same default root disk size on all images.
However, only GCE image specifies 20GB disk size, we should increase it
to 30GB (AWS and Azure default).
Note: we don't set default size on Azure build, but default disk size on
Azure is 30GB.

gce: increase disk size to 30GB

---

packer/build_deb_image.sh
packer/scylla.json
packer/scylla_install_image

Since today we are creating AMI for both `x86` and `arm` we should have
2 manifast files to upload.
Adding arch prefix so they will not override each other
This is a preparation for https://github.com/scylladb/scylla-pkg/issues/1869

[ami]:Add to scylla-packages manifast file arch prefix

---

common/scylla_configure.py
common/scylla_create_devices
tests/test_scylla_configure.py

With commit https://github.com/scylladb/scylla/commit/42fd73d0332d034809c6cd228785bff82e1845aa
support RAID 5 was added to scylla.
Added appropriate parameter to scylla_configure and
scylla_create_device --raid-level parameter
for configure scylla ami
Issue: https://github.com/scylladb/scylla-machine-image/issues/265

scylla_create_device: Add support --raid-level parameter

---

packer/build_deb_image.sh

In 63ab4ae3a1e950a5c32fd8b7c532772b8bb76b25 i have added another variable to packer with the arch type. By mistake it was added to all cloud providers rather then only AWS
Fixing it

fix(build_deb_image.sh): set arch var only for AWS

---

packer/build_deb_image.sh
packer/scylla.json
packer/scylla_install_image

Following the work in https://github.com/scylladb/scylla-machine-image/pull/97/commits/e2243830305066756138943f291b85565f72709c
manifest creation is failing in enterprise since we use `scylla` as hard coded rather then product name
Fixing it

fix(scylla_install_image):create manifast based on product name

---

packer/scylla.json
packer/scylla_install_image

Later in the process of building the AMI we need to upload to S3 for future use.
Adding into manifest filename the current Scylla version

scylla_install_image:add Scylla version to manifest filename

---

packer/build_deb_image.sh

During artifacts-ami-test-arm in 4.6 we got the following error:
```
Launch Failed
The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.
```
@benipeled pointed out that we are using a worng based ami for arm.
Fixes: 	https://github.com/scylladb/scylla-pkg/issues/2659

[ami]:modify arm based ami

---

packer/build_deb_image.sh
packer/build_image.sh
packer/scylla.json

We currently hardcoded source AMI ID, it may outdated if we keep using old one.
To automatically use latest image for source AMI, drop source_ami and
switch to source_ami_filter to find latest image by name pattern and owner id.

aws: find latest image for source AMI

---

packer/scylla.json

Today in scylla-pkg we search the log for the created AMI/Gce/Azure image.
There is an option when building image with packer to auto create a manifest with the relevant information , this will allow us to send the functions the value instead of looking for it

build_deb_image.sh: create image manifest with image ID

---

SCYLLA-VERSION-GEN

We decided to name the next version Scylla 5.0, in honor of
Raft based schema management.

prepare for Scylla 5.0

---

packer/build_image.sh

On latest master CentOS image build is broken because we added "arch" and "product" variables on Packer.
To fix it we need to add them to build_image.sh too.

Fix CentOS image build

---

common/scylla_cloud_io_setup
common/scylla_configure.py
common/scylla_create_devices
common/scylla_ec2_check
common/scylla_image_setup
common/scylla_login
common/scylla_post_start.py
dist/debian/debian/rules
dist/redhat/scylla-machine-image.spec
lib/scylla_cloud.py
packer/scylla_install_image

Currently, cloud related code have cross-dependencies between
scylla and scylla-machine-image.
It is not good way to implement, and single change can break both
package.
To resolve the issue, we need to move all cloud related code to
scylla-machine-image, and remove them from scylla repository.
Here's change list:
- move cloud part of scylla_util.py to lib/scylla_cloud.py
- move cloud part of scylla_io_setup to common/scylla_cloud_io_setup
- move scylla_ec2_check to common/
- merge scylla_bootparam_setup to packer/scylla_install_image
---- 
This is scylla-machine-image part of the PR, please merge this part first.

move cloud related code from scylla repository to scylla-machine-image

---

dist/redhat/build_rpm.sh

Centos8 become EOL. need to modify mirror to keep using it for our
installations

fix(centos8): Centos8 is EOL, need to change mirrors

---

lib/scylla_cloud.py

This fixes "NameError: name 'glob' is not defined" error.
Fixes #294

scylla_cloud.py: import missing 'glob' module

---

packer/scylla_install_image

Today when we create the manifest we separate the package name and version by `-` , this fail the upgrade process since when we need to  install specific version apt-get expect us to separate package name and version with `=`
Fixing it

fix(manifest):separate package name from version with `=`

---

aws/cloudformation/scylla.yaml.j2

This is a preparation for https://github.com/scylladb/scylla-pkg/issues/2616. In order to support AMI promote for arm based arch, we need to generate the cloudformation yaml file based on the relevant instance types
Adding a condition based on parameter that we will pass during the template generating process
Thanks to @benipeled for the providing the quick solution

cloudformation:Add support arm based machines

---

common/scylla_login

Just like 3d01592, scylla_login requires to rename older disk function
name to current one.

scylla_login: Fix more no attribute 'getEphemeralOsDisks' error

---

common/scylla_image_setup
packer/scylla_install_image

Swap creation on scylla-image-setup.service is too much time, it slows down
startup of scylla-server.service on our IaaS image.
To fix the issue, pre-allocate swapfile while building the image.
Use half of diskfree to swap size, since it is maximum size allowed on
scylla_swap_setup and should be enough for any instance types.
Fixes #285
----
Please merge this only after https://github.com/scylladb/scylla/pull/9971 merged.

pre-allocate swapfile while building image

---

aws/cloudformation/test_scylla_cfn.py
common/scylla_configure.py
common/scylla_create_devices
common/scylla_ec2_check
common/scylla_image_setup
common/scylla_login
common/scylla_post_start.py
dist/debian/build_deb.sh
dist/debian/debian_files_gen.py
dist/redhat/build_rpm.sh
k8s/build_image.sh
k8s/scylla_k8s_node_setup
lib/log.py
lib/scylla_cloud.py
lib/scylla_cloud_io_setup.py
packer/build_deb_image.sh
packer/build_deb_with_docker.sh
packer/build_image.sh
packer/build_with_docker.sh
packer/scylla_install_image
tests/test_scylla_configure.py
tools/relocate_python_scripts.py

This is scylla-machine-image version of scylladb/scylla#9937
----
Instead of lengthy blurbs, switch to single-line, machine-readable
standardized (https://spdx.dev) license identifiers. The Linux kernel
switched long ago, so there is strong precedent.
Note that dist/debian/debian_files_gen.py is replaced from AGPL to Apache
since applying AGPL was mistake.

treewide: use Software Package Data Exchange (SPDX) license identifiers

---

common/scylla_image_setup
packer/scylla_install_image

Similar with #285, we can move scylla_coredump_setup to image building time except enabling bind-mount RAID volume to /var/lib/systemd/coredump.
Fixes #299

Move scylla_coredump_setup to image building time

---

common/scylla_configure.py
tests/test_scylla_configure.py

Currently, when scylla_on_first_boot set to false, scylla-server.service
becomes failed state by returning non-zero in scylla_prepare script.
But systemd may automatically tries to start scylla-server.service again
when daemon is reloaded or any other services is manipulated.
Instead, we should make scylla-server.service stopped state, by running
systemctl stop scylla-server.service.
Fixes #234

make scylla-server.service stopped state when scylla_on_first_boot=false

---

lib/scylla_cloud.py
tests/test_aws_instance.py

aws_instance.get_local_disks() and aws_instance.get_remote_disks()
should return list instead of set, since we do so in gcp_instance and
azure_instance.
Fixes #315

aws_instance: change get_local_disks()/get_remote_disks() to return list

---

common/scylla_image_setup

Added missing ",".
Signed-off-by: Takuya ASADA <syuu@scylladb.com>

scylla_image_setup: fix typo on run()

---

gce/image/scylla_gce.json

[](https://github.com/yaronkaikov)Since centos8 is EOL, we need to switch to centos-stream-8 to continue
supporting gce images (which are rpm based).

gce:Build image based on Centos-Stream-8 instead of centos8 

---

aws/ami/files/elrepo-archive.repo
aws/ami/files/scylla_install_ami

This is fix for branch-4.4
----
On kernel-ml 5.16.x, the kernel fails to initialize ENA driver (NIC),
not able to login to the instance since network is offline.
As workaround fix, pin down kernel version to 5.15.8 until we find root
cause of the problem.
fixes #332

ami: Workaround for NIC driver failure on kernel-ml 5.16.x

---

dist/debian/build_deb.sh
packer/scylla_install_image

In https://github.com/scylladb/scylla-machine-image/pull/334/commits/434795fcd0522457d843dfb695f46493330486d0
snap installation was removed and we started to use ssm-agent deb package. Since we are building AMI based on ARM as well. we need to support both arches

scylla_install_image:add ssm-agent installation for arm

---

.github/workflows/build.yml

on newer git version we are getting the following error when
running a test under docker:
```
fatal: unsafe repository (REPO is owned by someone else)
```
https://github.com/actions/checkout/issues/760

Fix build errors when newer git it used (fatal: unsafe repository)

---

packer/build_deb_image.sh

When QA running jobs which are relaying on recent AMI, the first run `hydra list-ami-branch -r eu-west-1 master:all`
The query looks for AMI with tag name `BRANCH=master`. when building local AMI for debug if no `--branch <name>` is provided we have a default of `master` , removing the default so QA will get the only relevant images
Closes: https://github.com/scylladb/scylla-pkg/issues/2856

build_deb_image.sh:remove default tag for branch name

---

common/scylla_image_setup

Some distro has fstrim enabled by default, since we
are using XFS with online discard, we don't need fstrim
running
Fixes: #341

XFS online discard: Disable fstrim.timer if active

---

common/scylla_cloud_io_setup
dist/debian/debian/rules
dist/redhat/scylla-machine-image.spec
lib/scylla_cloud.py

The decision converting scylla_cloud_io_setup to python library was mistake,
since there are some users who wants to construct IaaS image by themselves,
not using our official image.
They will need to invoke scylla_cloud_io_setup from shell, not python.

revert converting scylla_cloud_io_setup to python library

---

packer/scylla.json

During my debug sessions i saw the following message:
```
09:34:04  ␛[1;32m==> aws: Waiting for AMI to become ready...␛[0m
10:04:13  ␛[1;31m==> aws: Error waiting for AMI: Failed with ResourceNotReady error, which can have a variety of causes. For help troubleshooting, check our docs: https://www.packer.io/docs/builders/amazon.html#resourcenotready-error
10:04:13  ==> aws: original error: ResourceNotReady: exceeded wait attempts␛[0m
```
So the AMI job fails but if we check AWS console after few more minutes
we see that the AMI was successfully have been created.
Let's increase the amount of time packer waits to avoid this

[ami]:increase amount of time for waiting to AMI to be ready

---

lib/scylla_cloud.py
lib/scylla_cloud_io_setup.py

Now that new `i4i` instance types are available, let's add them to our
supported instance types

scylla_cloud.py:Add support for i4i instance type

---

lib/scylla_cloud.py

method `self.is_unsupported_instance_class()` always was returning `False` making `is_recommended_instance` always return `False` causing error in io_setup

azure: fix is recommended instance method

---

packer/scylla_install_image

recently during cloud image build i getting sporadic failures with the following message:
```
14:07:33  ␛[1;31m==> azure: E: Unable to locate package systemd-coredump␛[0m
14:07:34  ␛[1;31m==> azure: Traceback (most recent call last):␛[0m
14:07:34  ␛[1;31m==> azure:   File "/home/azureuser/scylla_install_image", line 108, in <module>␛[0m
14:07:34  ␛[1;31m==> azure:     run('apt-get install -y --allow-unauthenticated {0}-machine-image {0}-server-dbg systemd-coredump'.format(args.product))␛[0m
14:07:34  ␛[1;31m==> azure:   File "/home/azureuser/scylla_install_image", line 28, in run␛[0m
14:07:34  ␛[1;31m==> azure:     return subprocess.check_call(cmd, shell=shell, env=my_env)␛[0m
14:07:34  ␛[1;31m==> azure:   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call␛[0m
14:07:34 …
```

scylla_install_image:install systemd-coredump before Scylla

---

lib/scylla_cloud.py
tests/test_aws_instance.py

Currently, our AMI fails to start scylla-image-setup when the instance
configured as "Metadata version: V2 only".
To fix this we need to implement IMDSv2 support on aws_instance class.
Fixes scylladb/scylla#9987

AWS: Support IMDSv2 on aws_instance

---

packer/scylla_install_image

in https://github.com/scylladb/scylla-machine-image/pull/368/commits/69d9a7a5f855e631f6a692ed8f8270321229b6e0 `homedir` parameter was removed, causing Azure image to fail since the home dir is not `/home/ubuntu/`
Fixing it

scylla_install_image: add `homedir` parameter

---

.github/workflows/build.yml

The rockylinux docker-image no longer has the `latest` tag

ci: fix rockylinux docker-image tag

---

SCYLLA-VERSION-GEN
dist/debian/build_deb.sh
dist/debian/debian_files_gen.py
dist/redhat/build_rpm.sh

Scylla-operator require Scylla to have semantic versioning. (Ref: https://semver.org/)
release candidate versioning already being updated in machine-image (https://github.com/scylladb/scylla-machine-image/pull/359/commits/e36e5a7260684f72f845e148d0822569631f27bd)
Nightly builds should be also aligned with this change
Ref: https://github.com/scylladb/scylla/issues/9543

SCYLLA-VERSION-GEN: use semver-compatible version

---

packer/build_deb_image.sh
packer/scylla.json

Following https://github.com/scylladb/scylla-machine-image/pull/371 removing old hacks we did for the old version convention

images:align images to new version convention

---

lib/scylla_cloud.py
lib/scylla_cloud_io_setup.py

We need to make sure that instances with no pre-configured IO, will run
`iotune` during the boot (as part of scylla-image-setup service),
@tarzanek the `run_iotune` function added on scylla_cloud_io_setup is a copy-paste of the original function you added [1] but without the cpuset/smp flag condition - not sure it's required - please take a look,
I verified this change on r5d.xlarge and i4i.xlarge and it works as expected but the fallback skipped for r5.xlarge since it's not part of the supported instance list [1] - what was the original behavior? did this work for diskless instances like r5.xlarge as well?
[0] https://github.com/scylladb/scylla-enterprise/blob/af3da2d7ac8b83e1710c418b269c3c85bd1fdbe4/dist/common/scripts/scylla_io_setup#L113-L165
[1] 'i2', 'i3', 'i3en', 'c5d', 'm5d', …

image-setup: run iotune for instances with no pre-configured io

---

packer/scylla.json

[Azure]:fix coredump installation failure

---

README.md
source/user_data_v3.rst

the structure in the example was wrong, `start_scylla_on_first_boot`
and `post_configuration_script` shouldn't be under `scylla_yaml`
they should be it's siblings

fix yaml user-data docs

---

packer/build_deb_image.sh
packer/scylla_install_image

As part of the apt-key deprecation [0], we need to use gpg to consume the
repo key and change the repo file (scylla.list) to explicitly point
to the key,
This is a chick-and-egg change because the repo file should be changed
on pkg repo and once it changed, the gpg command (added on this commit)
is required,
For this reason, we'll start with adding the gpg and later we'll remove the apt-key refs
In this change I also add the `sS` flag to the curl command to make it silent but print errors if there are such,
In addition, I removed the `--allow-insecure-repositories` which AFAIK is not require so better to avoid such a flag
Ref https://github.com/scylladb/scylladb/issues/11186
[0] https://wiki.debian.org/DebianRepository/UseThirdParty

ubuntu: move from apt-key command to gpg

---

.github/workflows/build.yml
common/scylla_configure.py
common/scylla_post_start.py
dist/debian/debian/rules
dist/redhat/scylla-machine-image.spec
lib/scylla_cloud.py
lib/user_data.py
test-requirements.txt
tests/test_aws_instance.py
tests/test_azure_instance.py
tests/test_gcp_instance.py
tests/test_scylla_configure.py
tests/test_scylla_post_start.py

code reading `post_start_script` wasn't aware of the mine multipart
support that was add recently, refactored the code so the reading
of the user_data is share between `scylla_configure.py` and
`scylla_post_start.py`
also added unit test for `scylla_post_start.py` to verify
this is working

refactor `scylla_post_start.py` to share user_data code

---

common/scylla_create_devices
common/scylla_ec2_check
common/scylla_login
lib/scylla_cloud.py

We currently does not able to get any error message from subprocess when we specified capture_output=True on subprocess.run().
This is because CalledProcessError does not print stdout/stderr when it raised, and we don't catch the exception, we just let python to cause Traceback.
Result of that, we only able to know exit status and failed command but
not able to get stdout/stderr.
To resolve this, add wrapper function "out()" for capture output, and
print stdout/stderr with error message inside the function.
This is scylla-machine-image version of https://github.com/scylladb/scylla/pull/10391

print subprocess error message when capture_output=True

---

packer/scylla_install_image

This remove more unneeded packages on Ubuntu image, includes:
- accountsservice
- udisks2
And also disable polkit.service by default since it almost unneeded but some CLI commands requires that, so let D-Bus to autostart the service when the API invoked.

ubuntu: drop more unneeded packages 

---

packer/build_deb_image.sh

Today we based our ami arch based on the local machine the process is running in. meaning that for building both x86 and arm AMI image (for same commit) we need to run on 2 different machines. Adding `arch` param so we can manually select which arch we want to build with.
default will remain the same (based on local machine)

[ami]:Add parameter to select which arch to use

---

packer/build_deb_image.sh

Following 4513c7c5473683dad7dd20048fa04e87f903f811, during the work on scylla-pkg side, i realized i was using the wrong `arch` parameter
Fixing it

[build_deb_image]:fix wrong arch parameter

---

packer/scylla_install_image

Microsoft recommends to use "Resource Disk" to store swap file, which is mounted at /mnt by default.
So let's use /mnt as swap directory for Azure, and use / as other IaaS.
Fixes #398

azure: use "Resource Disk" to store swap file

---

common/scylla_cloud_io_setup

The io setup flow is done early in the code as part of the `self.save()` or by running
the scylla_io_setup script in case of an instance with no pre-configured io
Fix #402
/cc @syuu1228

fix(machine-image-setup): remove redundant call to io setup

---

packer/scylla.json
packer/scylla_install_image

To provide kernel version information of the machine image, add kernel version metadata file which works like scylla-packages.txt.
See scylladb/scylla-pkg#3118

Add kernel version metadata file

---

common/scylla_configure.py
common/scylla_post_start.py
dist/redhat/build_rpm.sh
lib/scylla_cloud.py
test-requirements.txt

Using traceback_with_variables module, generate more detail traceback
with variables into debug log.
This will help fixing bugs which is hard to reproduce.
This is scylla-machine-image version of https://github.com/scylladb/scylla/pull/10472.
Please merge this only after https://github.com/scylladb/scylla/pull/10472 get merged, otherwise we will fail to load traceback_with_variables.

generate debug log when exception occurred

---

packer/ami_variables.json
packer/azure_variables.json
packer/build_image.sh
packer/build_with_docker.sh
packer/gce_variables.json
packer/scylla.json
packer/user_data.txt

On scylladb/scylla-machine-image@a7eac3d Takuya "merged" a few similar scripts that use packer to buile images (AMI, GCE, Azure) into one.
Let's set pkg to use the merged script.
Closes: https://github.com/scylladb/scylla-pkg/issues/2374
Should be merge together with: https://github.com/scylladb/scylla-pkg/pull/2976

build_deb_images.sh: use the unified script to build all images

---

packer/build_image.sh
packer/scylla_install_image

This commit bumps the image base-version to Ubuntu 22.04
**Note:** this change is currently blocked by cloudformation issue [0], if it will not going to fix soon, we'll need to use a workaround to adjust the python modules paths as suggested on [0]
[0] https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1304
Fix #390

machine-image: change base image to Ubuntu 22.04

---

packer/scylla.json

This commit changes the default post-behavior to make sure we have no packer leftovers
From packer amazon-ebs module page [0]:
> "Automatically terminate instances on shutdown in case Packer exits ungracefully. Possible values are stop and terminate. Defaults to stop."
[0] https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#shutdown_behavior
Ref https://github.com/scylladb/scylla-pkg/issues/3152

packer: terminate ec2 instances following non-stable packer-build

---

packer/build_image.sh
packer/scylla.json

Today we are using for both Image name and tag the same sets of parameters. let's use one definition instead
Closes: https://github.com/scylladb/scylla-machine-image/issues/385

[scylla.json]:remove duplication with image_name and tags

---

packer/build_image.sh
packer/scylla.json

Adding the `--build-mode` parameter to support building our images in debug
mode. This is just a preparation change, the actual change will be
part of Scylla-pkg
Ref: https://github.com/scylladb/scylladb/issues/5232

[images]:Add parameter to support build image in debug mode

---

common/scylla_image_setup
packer/scylla_install_image

Note that this is machine-image part of https://github.com/scylladb/scylladb/pull/12043
----
Since we dropped --no-bootparam-setup and --ami on scylla repo, we should drop it from machine-image too.
Related with #61

drop deperecated scylla_setup parameters

---

packer/build_image.sh
packer/scylla_install_image

This PR contains the following commits: 
[[Images]: remove services which we don't need during image creation](https://github.com/scylladb/scylla-machine-image/commit/afd033cddea34f43dfd6dbfd119a367597ed0d3a)
[[images]:Switch images to be based on ubuntu-minimal](https://github.com/scylladb/scylla-machine-image/commit/3c10079e866611cf6d667d7ae992a11661f81e30)
Closes: https://github.com/scylladb/scylla-machine-image/issues/408

[images]: remove services which we don't need and change our base OS to ubuntu-minimal

---

aws/cloudformation/scylla.yaml

Update AWS CloudFormation template to include statements about stack deployment time and discouraging AWS root user usage.

Update AWS CloudFormation template

---

lib/scylla_cloud.py
tests/test_gcp_instance.py

although it's not recommended by GCP, we need to remove the restriction for minimum cpu's when using 16 local disks or more. This is so we can support one of our cloud customer which is using this configuration
Closes: https://github.com/scylladb/scylla-enterprise/issues/2543

lib/scylla_cloud.py: remove diskCount vs cpu restrictions

---

lib/scylla_cloud.py
tests/test_gcp_instance.py

although it's not recommended by GCP, we need to remove the restriction for minimum cpu's when using 16 local disks or more. This is so we can support one of our cloud customer which is using this configuration
Closes: https://github.com/scylladb/scylla-enterprise/issues/2543

v2: lib/scylla_cloud.py: remove diskCount vs cpu restrictions

---

packer/scylla.json
packer/scylla_install_image

Microsoft provides a certification test API that can be used to evaluate a given image's sanity. They also provide which test cases they run and expect us to comply with, as well as their recommendations for Azure Marketplace Images.
The following have been flagged within the VM self-test output for our
latest image:
```
"TestCaseName": "Swap Partition on OS Disk",
"Description": "Verifies that no Swap partitions are created on the OS disk.",
"Result": "Failed",
"ActualValue": "Swap space configured on the OS disk.",
```
Was fixed in #400
```
"TestCaseName": "Required Kernel Parameters",
"Description": "Verifies the following kernel parameters are set console=ttyS0, earlyprintk=ttyS0, rootdelay=300",
"Result": "Warning",
"ActualValue": "Missing Parameter: rootdelay=300\r\nMatched …
```

[Azure]:make our image MS certified

---

packer/scylla.json
packer/scylla_install_image

Microsoft provides a certification test API that can be used to evaluate a given image's sanity. They also provide which test cases they run and expect us to comply with, as well as their recommendations for Azure Marketplace Images.
The following have been flagged within the VM self-test output for our
latest image:
"TestCaseName": "Swap Partition on OS Disk",
"Description": "Verifies that no Swap partitions are created on the OS disk.",
"Result": "Failed",
"ActualValue": "Swap space configured on the OS disk.",
Was fixed in #400
```
"TestCaseName": "Required Kernel Parameters",
"Description": "Verifies the following kernel parameters are set console=ttyS0, earlyprintk=ttyS0, rootdelay=300",
"Result": "Warning",
"ActualValue": "Missing Parameter: rootdelay=300\r\nMatched Parameter: …
```

[Azure]:make our image MS certified V.2

---

common/scylla-image-setup.service
common/scylla_image_setup
packer/scylla_install_image

Since "Resource Disk" is ephemeral, we cannot configure swapfile on machine image building time. So e7e7daa was incorrect, we currently mistakenly using rootfs for swapfile.
We need to allocate it on instance startup time, not machine image building time. And also it should executed after "Resource Disk" mounted to /mnt.
Fixes #431

azure-image: fix "Resource Disk" support for swapfile

---

packer/scylla.json

Due to a lack of resources in our main region EASTUS, we need to copy our images to different regions. In order to do it we need to keep the OS_disk during our main azure image creation.
So instead of creating a temp resource group for every build, I have created one for building purposes only.
Also keeping the original OS disk so we can later copy those images to different regions.
While doing it, I saw it also solves the retry for deleting resources we saw during Azure builds
Refs:  https://github.com/scylladb/scylla-pkg/issues/3165

[Azure]: save OS disk during image creation

---

packer/scylla_install_image

Since we want maximum performance and low latency, we need to disable deeper C-states on instances.
Fixes #425

Limit deeper C-states to reduce latency

---

packer/scylla.json

Currently, Azure image does not show Scylla login prompt when logging in to ssh, since /etc/skel/.profile does not copied to ~/.profile. To fix this, we need to copy the file while build the Azure image.

azure: show login prompt correctly

---

packer/build_image.sh
packer/scylla.json

Similar to https://github.com/scylladb/scylla-machine-image/pull/413/commits/300537dbb11f962972742bf8fd5097fb6fffcae7,
moving both Azure and Gce to be based on minimal image

[Azure,Gce]:build image based on minimal ubuntu22.04

---

packer/scylla.json

During image creation, we are running `apt-get full-upgrade which also updates the kernel (added as part of
https://github.com/scylladb/scylla-machine-image/commit/90340275b80a3a54dcfc1e5ec660481ba167d1c3),
Since we want to use the LTS kernel version only, adding the kernel removal package and installation before we run `scylla_install_image`
Currently only AWS and Azure have LTS kernel for 22.04, once GCP will
have it as well we should add it as well
Ref: https://github.com/scylladb/scylladb/issues/13560

(ami,azure):Install latest LTS kernel during image build 

---

k8s/Dockerfile
k8s/aws_scylla_create_devices
k8s/build_image.sh

K8s node setup image which was created 2 years ago was used in scylla-operator EKS example. This image was supposed to set up a RAID array, create XFS filesystem and mount it in desired location using helper scripts taken from this repository and from scylla image. 
Image was based on Scylla 4.1 which some time ago ended it's life and it's repository was removed. 
This cause failures for k8s image users becasue repository added in base image is no longer there. 
```
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
* base: download.cf.centos.org
* epel: d2lzkl7pfhq30w.cloudfront.net
* extras: download.cf.centos.org
* updates: download.cf.centos.org
http://downloads.scylladb.com/rpm/unstable/centos/branch-4.1/2020-08-31T00%3A50%3A11Z/scylla/x86_64/repodata/repomd.xml: [Errno …
```

Disable EOL scylla repositories in k8s node setup image

---

packer/scylla_install_image

disabling ntp configuration during image creation so we will use the default
cloud recommended configuration
Closes: https://github.com/scylladb/scylladb/issues/13344

fix(images):use default NTP configuration

---

packer/scylla.json

following the changes in 42e05cacdedcbabf1d416e32eeb2cf317b9669f5, during the package removal, forgot to change one of the packages to use cloud provider based on parameter rather then hardcoded
Fixing it

scylla.json: fix kernel removal for Azure

---

packer/build_image.sh

When trying to copy Azure image to other regions (on enterprise only), we get the following failure:
```
10:23:45  ERROR: command failed: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--resource-group', 'image-copy-rg', '--name', 'scylla-enterprise-2023.2.0-dev-x86_64-2023-05-01T09-12-36_os_disk_snapshot-eastus2', '--location', 'eastus2', '--source', 'https://eastus2lalnrozwewefc0at6.blob.core.windows.net/snapshots/scylla-enterprise-2023.2.0-dev-x86_64-2023-05-01T09-12-36_os_disk_snapshot.vhd', '--source-storage-account-id', '/subscriptions/****/resourceGroups/image-copy-rg/providers/Microsoft.Storage/storageAccounts/eastus2lalnrozwewefc0at6', '--hyper-v-generation', 'V2', '--output', 'json', '--subscription', ****, '--tags', …
```

[azure]:fix copy image due to long image name

---

packer/build_image.sh

Started to get an error during arm ami build:
```
09:53:19  [1;31m==> aws: Error launching source instance: InsufficientInstanceCapacity: We currently do not have sufficient a1.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get a1.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1c, us-east-1d.
```
Switching to more common instance type (the basic type we are also using for testing) , `im4gn.xlarge`

ami-arm: change instance type during image build

---

packer/scylla.json
packer/scylla_install_image

Today when we create images we have the same file name for all cloud images.
Let's generate a cloud specific kernel filename
Ref: https://github.com/scylladb/scylla-pkg/pull/3406

(images):create kernel-version output with cloud source

---

.github/workflows/build.yml

github action is failing with the following error:
```
fatal: unsafe repository ('/scylla-machine-image' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /scylla-machine-image
fatal: unsafe repository ('/scylla-machine-image' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /scylla-machine-image
Error: Process completed with exit code 128.
```

build.yml: fix git permission bug for checkout dir

---

packer/scylla.json

Based on https://packages.ubuntu.com/jammy-updates/linux-gcp-lts-22.04 gcp has now an official lts for 22.04
Closes: https://github.com/scylladb/scylla-machine-image/issues/452

(gcp): Use lts kernel version

---

packer/ami_variables.json
packer/scylla.json

fix for ERROR: "im4gn.xlarge capacity issue in Availability Zone (us-east-1b)" during AMI creation with packer build.
`subnet_id` variable changed to `subnet_filter` with `tag:Name` and `random` selection, which includes few available subnets (and not one dedicated subnet).
It also allow us to be more dynamic and update `tag:Name` of subnets in AWS config directly - to remove or add subnets

change subnet_id to subnet_filter in json config

---

packer/scylla.json

After adding the `pause_before` param on db75e41 I saw that we have SSH connection issues, so in this PR I'm increasing the pause to 20s and adding the `ssh_read_write_timeout` param
Example failure:
```
10:08:16  [1;32m==> aws: Pausing 10s before the next provisioner...[0m
10:08:27  [1;32m==> aws: Uploading files/ => /home/ubuntu/[0m
10:08:30  [1;31m==> aws: Upload failed: dial tcp 54.198.229.78:22: connect: connection refused[0m
10:08:30  [1;32m==> aws: Provisioning step had errors: Running the cleanup provisioner, if present...[0m
10:08:30  [1;32m==> aws: Terminating the source AWS instance...[0m
10:09:36  [1;32m==> aws: Cleaning up any extra volumes...[0m
10:09:36  [1;32m==> aws: No volumes to clean up, skipping[0m
10:09:36  [1;32m==> aws: Deleting temporary …
```

packer: increase pause_before value and add ssh_read_write_timeout

---

packer/ami_variables.json
packer/build_image.sh
packer/scylla.json

d84794b7b17a614fd64cc63aea0fcb0674920453 - ami valiables updated to use releng account
5ac4d127939c6c51dfa50664a1de98399b884e37 - adding an option of `ami_users` - adding permissions to AMI during packer build
Should be merged together with: https://github.com/scylladb/scylla-pkg/pull/3392

ami_variables: update aws variables for releng account

---

packer/scylla_install_image

during our rolling-upgrade process, we keep getting the following failure:
```
Command: 'sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" upgrade -y '
Exit code: 100
Stdout:
linux-aws linux-headers-aws linux-image-aws
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up shim-signed (1.40.9+15.7-0ubuntu1) ...
mount: /var/lib/grub/esp: special device /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol0b2a94761ddb1d0c5-part15 does not exist.
dpkg: error processing package shim-signed (--configure):
installed shim-signed package post-installation script subprocess returned error exit status 32
Errors were …
```

scylla_install_image:remove /var/cache/debconf/config.dat after image creation

---

packer/scylla_install_image

On AWS and Azure Ubuntu Minimal image we don't have rsyslog, it just uses persistent journal log, but only GCE image has rsyslog. We want to align image configuration between clouds, let's drop rsyslog from GCE image.
Related scylladb/scylla-enterprise#3080

gce: drop rsyslog

---

common/scylla_cloud_io_setup

Since we merged https://github.com/scylladb/scylladb/commit/817f34d1a94a1daa1e8591c93a047081d51f5628, we are missing preset configuration for c5d, m5d, m5ad, r5d, z1d. On such instance, our AMI causes error during startup (see scylladb/scylladb#9660).
To fix the problem, we need to add preset configuration for these instance types.

scylla_cloud_io_setup: add preset configuration for all supported instance types on EC2

---

common/scylla_cloud_io_setup

Since ecdbd44b5661cd8e97fec18c1d74a311ec4c2fa7 was bring from scylla_io_setup patch, there are incompatible variable names. We need to rename them in following rules:
- idata and disk_properties should be member of self
- rename instance_class() to instancetype

scylla_cloud_io_setup: fix NameError

---

lib/scylla_cloud.py

Following the changes in
https://github.com/scylladb/scylla-machine-image/pull/460, we need also to add `i4g` to list of instance_class
This will prevent the following error during image startup
```
Version:
5.4.0~dev-0.20230829.83ceedb18bdc
Nodetool:
nodetool help
CQL Shell:
cqlsh
More documentation available at:
https://docs.scylladb.com/
By default, Scylla sends certain information about this node to a data collection server. For more details, see https://www.scylladb.com/privacy/
i4g is not eligible for optimized automatic tuning!
To continue the setup of Scylla on this instance, run 'sudo scylla_io_setup'
then 'sudo systemctl start scylla-server'.
For a list of optimized instance types and more instructions, see http://www.scylladb.com/doc/getting-started-amazon/
```
Ref: …

scylla_cloud.py:Add `i4g` to supported instances

---

common/scylla_cloud_io_setup
lib/scylla_cloud.py

Adding pre-configure io_setup values
Also since `i4g` doesn't support enhanced networking adding it to use ENA

Add missing i4g.4xlarge instnace type

---

packer/scylla_install_image

On AWS and Azure Ubuntu Minimal image we don't have rsyslog, it just uses persistent journal log, but only GCE image has rsyslog. We want to align image configuration between clouds, let's drop rsyslog from GCE image.
Related scylladb/scylla-enterprise#3080
(cherry picked from commit a63350da21eddc2577604e182e73b7c54c59affb)

gce: drop rsyslog for branch-5.3

---

packer/scylla_install_image

On AWS and Azure Ubuntu Minimal image we don't have rsyslog, it just uses persistent journal log, but only GCE image has rsyslog. We want to align image configuration between clouds, let's drop rsyslog from GCE image.
Related scylladb/scylla-enterprise#3080
(cherry picked from commit a63350da21eddc2577604e182e73b7c54c59affb)

gce: drop rsyslog for branch-5.2

---

common/scylla_configure.py
common/scylla_login
lib/scylla_cloud.py

Currently, attempting to launch machine-image-setup on instances that don't meet scylla's requirements would result in setup failures,
This commit adds support for developer-mode instance types. when users launch these instances, scylla will run on `developer-mode`, and a WARN message will be displayed in the login message to inform users about the intended usage of these instances.
Fix: #477

Support developer-mode instance types

---

lib/scylla_cloud.py

Since IaaS services recommended to use exponential backoff logic when retries to call metadata services, we should do it in our scripts.
Referenced implementation in https://developers.google.com/analytics/devguides/reporting/core/v3/errors?hl=en
see https://docs.aws.amazon.com/general/latest/gr/api-retries.html
Related with scylladb/scylladb#13442

lib/scylla_cloud.py: change retry logic of curl() to exponential backoff

---

.gitignore
common/scylla_login
lib/scylla_cloud.py
test-requirements.txt
tests/test_aws_instance.py
tests/test_azure_instance.py
tests/test_gcp_instance.py

The previous links `/getting-started-google` and `/getting-started-azure` didn't exist
Ideally, we should refer to [0] but it's an OS page and I don't
want to add OS vs. Enterprise condition so for now let's go without a direct link
This PR also contains the following two minor changes
- https://github.com/scylladb/scylla-machine-image/commit/62752d746f4e0c789ea08a5c9bbc2a325b3a3a98 - Update gitignore
- https://github.com/scylladb/scylla-machine-image/commit/010fc98dc1be6c32a586ffe51e3eae83ae8abbef - Add boto3 as test-requirements
[0] https://opensource.docs.scylladb.com/master/getting-started/cloud-instance-recommendations

Fix broken link to the getting-started page

---

lib/scylla_cloud.py

Following the dev-mode instances support was added on https://github.com/scylladb/scylla-machine-image/pull/479
This change adds the t3.micro as AWS dev-mode instance
cc @carlosms

AWS: add t3.micro as dev-mode instance

---

README.md
common/scylla_configure.py
tests/test_scylla_configure.py

Following the changes done in https://github.com/scylladb/scylladb/pull/15233 . we need also remove the `Experimental` options in the machine-image
Closes: scylladb#484

scylla_conifgure.py: remove "experimental" option

---

packer/scylla_install_image

On latest master, re.sub() is failing since regex pattern is not matched with cloud.cfg on latest Ubuntu image.
To avoid such problem, we should use yaml module instead.

aws: use yaml module for cloud.cfg

---

packer/build_image.sh

This PR includes 2 commits:
- 780dd8753c90fad1b6933366fb64caf9bf8260c7 - change default INSTANCE_TYPE for ARM to im4gn.2xlarge
- 1bdf38e781ab40780d271a6825c90395fa51a723 - adding new 'ec2-instance-type' parameter

adding EC2 instance type option to use while building the AMI + change current default 

---

dist/debian/control.template
dist/redhat/scylla-machine-image.spec

When upgrading OSS to Enterprise we need to make sure `scylla-machine-image` will be replaced with `scylla-enterprise-machine-image` package
Adding `Obsoletes` indication in the .spec file and controle.template so scylla-enterprise-machine-image is a replacement for scylla-machine-image.
Closes: https://github.com/scylladb/scylla-enterprise-machine-image/issues/51
Closes: https://github.com/scylladb/scylla-enterprise-machine-image/issues/50

scylla-machine-image:replace package during upgrade

---

packer/scylla.json

Following an unknown SSH connection failure raised after the build-machine rebooted
Ref https://github.com/scylladb/scylla-pkg/issues/3646

packer: increase pause_before to 40 seconds

---

packer/scylla.json

packer/scylla.json: Add `apt-get update` after kernel package removal

---

packer/scylla.json

Until today,  all our images (and snapshots) are gp2 type.
We should move all to gp3 which is more cost effective and better performance
Closes: https://github.com/scylladb/scylla-machine-image/issues/495

ami: create with gp3 as volume_type

---

common/scylla_image_setup
packer/scylla_install_image

This reverts commit 069318bb48963aa5bede707579e499a8bd1288c4.
Related with #491, we need to reduce snapshot size of the rootfs, we should not pre-allocate swapfile while building image.

Revert "pre-allocate swapfile while building image"

---

packer/scylla.json

some minor changes following https://github.com/scylladb/scylla-machine-image/pull/494
remove `apt-get update` before purging the packages

scylla.json: remove extra `apt-get update` during kernel upgrade

---

packer/build_image.sh
packer/scylla_install_image

...and remove the old apt-get which is no longer required
Ref https://github.com/scylladb/scylla-pkg/issues/3738

gpg: add the 2024 pub key

---

lib/scylla_cloud.py
tests/test_aws_instance.py
tests/test_azure_instance.py
tests/test_gcp_instance.py

Currently get_cloud_instance() is very slow on GCE / Azure, since it fails to detect AWS metadata server, and retrying multiple times in curl().
Actually we don't really need to do detection, we can specify target cloud name statically when we build machine-image.
To do so, adding target cloud name to machine_image_info.yaml while building machine-image, and reference it from scylla_cloud.py.
Note that we still need to fallback to metadata server based detection, since there are users who manually install scylla-machine-image package , not using our machine-image.
Fixes #481

Optimize cloud detection

---

packer/build_image.sh

Following #389 we can now remove the apt-key refs

ubuntu: remove apt-key refs

---

common/scylla_configure.py
lib/scylla_cloud.py

user_data() is mistakenly unsupported IMDSv2, since it's not using __instance_metadata().
Fixed the code to use __instance_metadata().
Fixes #498

aws_instance: fix broken user_data()

---

packer/build_image.sh

Following the change made in https://github.com/scylladb/scylla-pkg/issues/3764. the redirect change
is now failing our image build process with the following error:
```
02:25:02  + bash -c 'set -o pipefail; /jenkins/workspace/scylla-master/ami/scylla-pkg/tools/packaging/dpackager -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -- ./build_image.sh --target aws --product scylla --repo downloads.scylladb.com/unstable/scylla/master/deb/unified/2024-03-05T21:07:35Z/scylladb-master/scylla.list --arch x86_64 --build-mode release --ami-regions us-west-2,eu-west-2,eu-west-1,eu-central-1,eu-north-1 --ami-users 797456418907 --log-file ami_x86_64.log    --build-id 1352 --build-tag jenkins-scylla-master-ami-1352 --branch master --scylla-build-sha-id …
```

[images] add https prefix to url

---

packer/scylla.json
packer/scylla_install_image

the 3rd party upgrade procedure was dropped from docs in https://github.com/scylladb/scylladb/issues/15733
Removing the code as we don't need it any more
Refs: https://github.com/scylladb/scylla-pkg/issues/3892

remove package manifest creation as it's not in use

---

.github/workflows/build.yml

as per @fruch,
> we are using our own python version from scylla-python3, and currently
> on master it's 3.11
so, let's test with the version we use in production. this should also unlock the features from the language and the standard library provided in higher versions of CPython.

build.yml: bump the python-version to 3.11

---

lib/scylla_cloud.py

this change is a follow-up of d97e311130, which caches the result of `identify_cloud_async()` using a global variable. it would be more idiomatic to use `functool.cache` for caching a costy function like `identify_cloud_async()`, so in this change we use it for caching. simpler this way. and more importantly, it is more readable.

lib/scylla_cloud: use functool.cache to cache identify_cloud_async()

---

packer/scylla.json

With this change, AMIs wil be shared with the entire aws scylla org (instead of specific accounts) to allow all accounts to use the AMI before it is promoted + avoid the need to maintain a list of accounts that require AMI access,
This is about the AMI, on another change on pkg we need to adjust the `change_snapshot_permissions()` function to loop through all the org account
Ref https://github.com/scylladb/scylla-pkg/issues/3529

packer: share AMIs with the entire aws scylla organization

---

packer/scylla_install_image

In order to reduce setup time for cloud, adding packages based on https://github.com/scylladb/siren-devops/blob/f5ddb43aeab16bc19695ae22692426e6d405e9e3/ansible/roles/cloud-base-image/tasks/main.yml#L20
Fixes: https://github.com/scylladb/scylla-enterprise-machine-image/issues/70

[cloud images] add packages for Scylla cloud deployments

---

packer/build_image.sh
packer/scylla.json

Following the work done in https://github.com/scylladb/scylladb/commit/b8634fb244ab08c2ffa66700745b06e21ee57f30, we no longer installing jmx and tools-java packages
Removing it from the machine image as well
This should be merged only after https://github.com/scylladb/scylladb/pull/18494

[cloud images] drop jmx and tools packages

---

packer/build_image.sh
packer/scylla.json

Following https://github.com/scylladb/scylla-pkg/pull/4002 the `--ami-users` flag is no longer in use

Remove unused flag ami-users

---

common/scylla_configure.py
common/scylla_create_devices
common/scylla_post_start.py
lib/scylla_cloud.py

On https://github.com/scylladb/scylla-machine-image/issues/498, status of scylla-image-post-start.service is NOT "failed" even
the script causing error, because scylla_post_start.py catches all
exceptions and just logging it, so the script finishes without error.
To getting notify users the script failed operation during running, we
should sys.exit(1) when the exception catched.
Also, when curl catched HTTP error 4xx = client error such as "404 Not Found"
or "403 Forbidden", it likely our script bug not server side issue, we
should re-raise exception immediately instead of retrying.
fixes https://github.com/scylladb/scylla-machine-image/issues/505

exit with 1 when Exception catched and raise exception when HTTP error code is client error

---

packer/scylla_install_image

scylla_raid_setup requires to install xfsprogs, mdadm, initramfs-tools. We should preinstall these packages while building machine image instead of starting scylla_image_setup, to speed up the instance boot process.
Related scylladb/scylladb#19651

scylla_install_image: preinstall scylla_raid_setup dependencies

---

common/scylla_login
packer/build_image.sh
packer/scylla.json
packer/scylla_install_image

As part of our work in scylladb/scylla-enterprise#4111
Updating our Images to the latest LTS Ubuntu
Also include a minor syntax fix - 9a642d3e79d0f6c20d0839e7c0bb5c897606dcb9
Fixes: scylladb#527

[images] build based on ubuntu24.04

---

packer/build_image.sh

A new GPG key was created for supporting both rpm and deb in RSA mode
Related to https://github.com/scylladb/scylla-enterprise/issues/4222

packer/build_image.sh: update GPG key

---

packer/scylla_install_image

Following the changes in 23bc340, it seems i missed a place for the gpg key replacement
adding it so we can run `apt-get update` inside our images
Fixes: https://github.com/scylladb/scylla-pkg/issues/4255

packer/scylla_install_image: update gpg key inisde the image

---

packer/scylla_install_image

Based on https://github.com/scylladb/siren-devops/issues/1764#issuecomment-2283469016 we should add those packages and remove `htop` for the cloud usage
Fixes: https://github.com/scylladb/siren-devops/issues/1764

[cloud images] Add vim-nox and sysstat to images

---

.github/scripts/auto-backport.py
.github/scripts/search_commits.py
.github/workflows/add-label-when-promoted.yaml

Similar to what we have in Scylla-pkg, adding relevant automation scripts and workflow so we can easly do backports

[machine-image] add backport automation

---

.github/scripts/auto-backport.py
.github/workflows/add-label-when-promoted.yaml

In this commit there few improvments to the backport automation process based on the work done in https://github.com/scylladb/scylla-machine-image/pull/541
1. Create new parameter `--commit` to be use only when `--pull-request` is provided
2. Trigger workflow when label is `backport/x.y` only, rather then `backport/` as it was defined before. This way we will not trigger to flow when `backport/x.y-done` was added
3. when running on specific PR with `--pull-request` make sure we don't pass an empty commit
4. fix `get_prs_from_commits()` while trying to do `get_commit` on the wrong sha1 value

[.github/scripts/auto-backport.py] improve label logic

---

.github/scripts/auto-backport.py
.github/workflows/add-label-when-promoted.yaml

Based on all changes done in scylla-pkg, updating machine-image for recent auto-backport working version

auto-backport: update init configuration

---

.github/scripts/auto-backport.py

It seems that we can't push branches to the developer's fork due to permission issues (I managed to get it working during my verification, but maybe it was because I was testing it under my user)
Since all Dev team members in Github have Triage permissions, they can't update branches under the scylladb organization, Instead, I have added write permission on `scyllaadbbot` fork to provide access to all dev This will allow everyone to update the backport branches directly when conflicts apply and in general

./github/scripts/auto-backport.py: use `scylladbbot` fork for backport PRs

---

.github/workflows/add-label-when-promoted.yaml

In #21496 (comment)
```
scylladbbot force-pushed the backport/21459/to-6.1 branch from 414691c to 59a4ccd Compare 2 days ago
```
Backport automation is triggered by push but should also start from the master branch (or enterprise branches from Enterprise). We need to verify it by checking the default branch.

./github/workflows/add-label-when-promoted.yaml: Run auto-backport only on default branch

---

common/scylla_configure.py
common/scylla_image_setup

Since dev_instance_type does not have local SSD, we should skip running scylla_create_devices.
Fixes #551

scylla_conifgure.py: skip construct data volume on dev_instance_type

---

.github/workflows/add-label-when-promoted.yaml

It seems that `DEFAULT_BRANCH` points to the repo default branch configuration. renaming it to `stable_branch` (as it should be) and using the output to pass the value for the if statement

.github/workflows/add-label-when-promoted.yaml: fixing expression

---

packer/build_image.sh

related to changes in https://github.com/scylladb/scylla-pkg/pull/4635, modifying the script to get `version` and `release` values from the pipeline to remove the constrain between dpackager OS and image OS
Should be merged with https://github.com/scylladb/scylla-pkg/pull/4635

packer/build_images.sh: get version and release values from pipline

---

common/scylla_image_setup
packer/scylla_install_image

It was mistakenly does not configured as expected, fixing. (Probably we broke this when we switched from Ubuntu minimal base image, since it does not have cpufrequtils)
Fixes #550

Install cpufrequtils and run scylla_cpuscaling_setup

---

packer/build_image.sh
packer/scylla.json

Adding a logic for the `environment` tag for better image search
The default value is set for `debug`
- master tag value will be `daily`
- releases, the tag value will be `candidate` (and we modify it to `production` once we promote)
- debug jobs (everything running under `machine-image` gating, `byo` or `releng-testing`) the value will be debug
There is one special case for private builds that will be handled in a separate PR
This is a prep for https://github.com/scylladb/scylla-pkg/issues/4077
Need to be merge only after https://github.com/scylladb/scylla-pkg/pull/4725

(cloud images): add `environment` default tag

---

.github/scripts/auto-backport.py
.github/workflows/add-label-when-promoted.yaml

Syncing a few changes that have already been implemented in scylla-pkg:
* remove condition for enterprise - since we are now running always from the `scylla-machine-image` repo
* run backport process from stable branch (which is `master`)
* improve conflict cases - by adding a comment to notify the PR owner
* pass label for each pull_request_target trigger

./github/scripts/auto-backport: align process to source available and more

---

.github/workflows/add-label-when-promoted.yaml

In https://github.com/scylladb/scylla-machine-image/pull/572 `run: echo "$GITHUB_CONTEXT"` line was removed by mistake causing the workflow to fail
Adding it back

.github/workflows/add-label-when-promoted.yaml: add missing `run` command

---

common/aws_io_params.yaml
lib/scylla_cloud.py

Adding preset io parameters of i7ie to scylla_cloud_io_setup, and also added i7ie to supported instance type on aws_instance class.
Closes #559

aws: add i7ie instance type

---

packer/build_image.sh

follow the commit 870d6a6ce7b6c5cb01f151f89b335b3d55ebe958  
the `ERROR: Illegal option: --env-tag` is displayed on build image process (ami, gce, azure)
seems this part is missing in the backport
adding it
Failed job: https://jenkins.scylladb.com/job/scylla-6.2/job/azure-image/10/
`00:06:37  ERROR: Illegal option: --env-tag`
Verification passed:
https://jenkins.scylladb.com/job/scylla-6.2/job/azure-image/11/

build_image: fix Illegal option `--env-tag`

---

dist/debian/control.template
dist/redhat/scylla-machine-image.spec

I think this is defined for scylla-enterprise-machine-image, but we shouldn't have it for OSS version.

dist: "Obsoletes: scylla-machine-image" is invalid for OSS version

---

dist/debian/control.template
dist/redhat/scylla-machine-image.spec

dist: support smooth upgrade from enterprise to source availalbe When upgrading for example from `2024.1` to `2025.1` the package name is not identical casuing the upgrade command to fail.
This makes packages upgradable from enterprise.
Related scylladb/scylladb#22420

dist: support smooth upgrade from enterprise to source available

---

dist/debian/control.template

Following d3b4dcd7277ad1c4d8c59b89fb6377d2ad7ad2ef next-machine-image failed with the following error:
```
17:28:21   dpkg-buildpackage -rfakeroot -us -uc -ui
17:28:22  dpkg-buildpackage: error: syntax error in debian/control at line 13: duplicate field Replaces found
17:28:22  debuild: fatal error at line 1184:
17:28:22  dpkg-buildpackage -rfakeroot -us -uc -ui failed
```

dist/debian/control.template: remove duplicate

---

common/aws_io_params.yaml

Add preset io parametter of i4i.12xlarge and i4i.24xlarge, which we mistakenly
did not added when we support i4i instance type on the commit https://github.com/scylladb/scylla-machine-image/commit/b7a00ecfedcc24dba54bf62d4ac6ffb308f27fb5.
Here's raw output of iotune:
- i4i.12xlarge (1/3)
Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 2182 MB/s (deviation 3%)
Measuring sequential read bandwidth: 2971 MB/s (deviation 7%)
Measuring random write IOPS: 67397 IOPS
Measuring random read IOPS: 297871 IOPS
- i4i.12xlarge (2/3)
Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 2181 MB/s (deviation 3%)
Measuring sequential read bandwidth: 2971 MB/s (deviation 7%)
Measuring random write IOPS: 67248 IOPS (deviation 4%)
Measuring …

aws: add missing instance size i4i.12xlarge and i4i.24xlarge

---

common/scylla_cloud_io_setup

This is branch-2024.1 version of https://github.com/scylladb/scylla-machine-image/pull/620.
Since we cannot backport  https://github.com/scylladb/scylla-machine-image/pull/620 because there is source code incompatibility on io parameters since we recently moved to aws_io_params.yaml, so the commit message does not include "cherry picked from".
----
Add preset io parametter of i4i.12xlarge and i4i.24xlarge, which we mistakenly did not added when we support i4i instance type on the commit b7a00ec.
Here's raw output of iotune:
- i4i.12xlarge (1/3) Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 2182 MB/s (deviation 3%) Measuring sequential read bandwidth: 2971 MB/s (deviation 7%) Measuring random write IOPS: 67397 IOPS
Measuring random read IOPS: 297871 …

aws: add missing instance size i4i.12xlarge and i4i.24xlarge for branch-2024.1

---

common/scylla_cloud_io_setup

This is branch-6.1 version of https://github.com/scylladb/scylla-machine-image/pull/620.
Since we cannot backport  https://github.com/scylladb/scylla-machine-image/pull/620 because there is source code incompatibility on io parameters since we recently moved to aws_io_params.yaml, so the commit message does not include "cherry picked from".
----
Add preset io parametter of i4i.12xlarge and i4i.24xlarge, which we mistakenly did not added when we support i4i instance type on the commit b7a00ec.
Here's raw output of iotune:
- i4i.12xlarge (1/3) Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 2182 MB/s (deviation 3%) Measuring sequential read bandwidth: 2971 MB/s (deviation 7%) Measuring random write IOPS: 67397 IOPS
Measuring random read IOPS: 297871 IOPS …

aws: add missing instance size i4i.12xlarge and i4i.24xlarge for branch-6.1

---

packer/scylla_install_image

currently, if the BYOA customer is assigned the required AWS Profile on the instance or will deploy scylla in GCP customer will able to fetch metadata about the OS itself, and also be able to execute a command on a target instance, which may lead to loose of control for instances deployed in BYOA.
Fixes: https://github.com/scylladb/scylla-pkg/issues/4883

scylla_install_image: disable cloud provider agents

---

.github/workflows/trigger_jenkins.yaml

This action will help preventing next-trigger and next-trigger-machine-image for running every 15 minutes.
This action will run on push for a specific branch. For now we'll start with releng-testing for the first tests
Fixes: #4853

Trigger Jenkins job using github action

---

.github/workflows/trigger_jenkins.yaml

Since enterprise releases such as 2024.2 are located under `enterprise-2024.2` folder.
Adding the support for all releases

trigger_jenkins: add support for old ent releases

---

.github/workflows/trigger_jenkins.yaml

rename the job location to `FOLDER_NAME` instead of `VERSION`

trigger_jenkins: fix typo for enterprise releases

---

.github/workflows/trigger_jenkins.yaml

Releases like 2024.1 or 2024.2 are falling under the regex rule for ^[0-9]+\.[0-9]+ To avoid it, we are changing the order of the regex rules so 2024.x falls under enterprise-$VERSION while 2025.x 6.x x.x falls under scylla-$VERSION
Relates to issue #4853

Fix trigger_jenkins action - FOLDER_NAME regex

---

.github/workflows/trigger_jenkins.yaml

Improves the way we trigger next-machine-image job using a dedicated github action instead of using curl.
Fixes: scylladb#659

Use github action instead of curl method to trigger jenkins

---

.github/workflows/trigger_jenkins.yaml

Before we were using a marketplace Github action which had some limitations. With this pull request we are updating the github action using curl option which will gives us full control of the flow instead of relying on pre made github action.
Fixes: scylladb#659

Update github action using curl method

---

packer/scylla_install_image

As it required by the cloud team
Fixes: https://github.com/scylladb/scylla-machine-image/issues/682

images: add netcat-openbsd package

---

.github/scripts/auto-backport.py

Currently adding a label backport-x.x is enough to open a backport PR.
The issue is that the github action is only checking for backport labels while the script if we have args.pull_request will ignore completely this label again.
With this fix I'm setting the check for labels including the promoted_label outside of the else statement. This way the script will always check it.
Refs: [scylladb#4979](https://github.com/scylladb/scylla-pkg/issues/4979)

Auto backport - promoted-to-master label not having effect

---

common/aws_io_params.yaml

Adding preset io parameters of i7ie to scylla_cloud_io_setup, and also added i7ie to supported instance type on aws_instance class.
All preset values are measured by iotune on target instances.
Fixes #692
Here's measurement environment details:
- Measured on i7ie.* instances with latest version of Ubuntu 24.04 LTS AMI (We cannot use Scylla AMI since we do want to measure single drive performance)
- Measured single local SSD w/o RAID0, since we simulate RAID0 performance on scylla_cloud_io_setup script from single drive performance
- Use iotune for the measurement, executed 3 times for each instance size and used average of the results
- Automated measurement by script: https://github.com/syuu1228/ec2_run_script
Here's raw output of iotune:
- i7i.large (1/3) Starting Evaluation. This may …

aws: add i7i instance type

---

.github/ISSUE_TEMPLATE /config.yml

There was a typo in the directory name (an additional space)

Delete .github/ISSUE_TEMPLATE  directory

---

common/gcp_io_params.yaml
common/scylla_cloud_io_setup
dist/debian/debian/rules
dist/redhat/scylla-machine-image.spec
tests/test_gcp_instance.py

- Add gcp_io_params.yaml with per-SSD specs for 11 z3 variants
- Align GCP I/O setup logic with AWS architecture (YAML + multiplication)
- Update package deployment for RPM/DEB
- Add test coverage for z3 instance class validation
Fixes: scylladb#724

Add support for the new z3 instances (GCP)

---

packer/apply_cis_rules

Advanced Intrusion Detection Environment (AIDE) is a intrusion detection tool that uses predefined rules to check the integrity of files and directories in the Linux operating system. AIDE has its own database to check the integrity of files and directories.
AIDE takes a snapshot of files and directories including modification times, permissions, and file hashes which can then be used to compare against the current state of the filesystem to detect modifications to the system.
By monitoring the filesystem state compromised files can be detected to prevent or limit the exposure of accidental or malicious misconfigurations or modified binaries.
This will apply following CIS compliance rules:
- xccdf_org.ssgproject.content_rule_package_aide_installed
- …

Verify Integrity with AIDE

---

packer/apply_cis_rules

We need to restrict root login on pam_wheel and single user login.
To do so, use group parameter on pam_wheel.so and specify allowed group to "sugroup", which permit `su` command only for the users who belongs to "sugroup".
This will apply following CIS compliance rules:
- xccdf_org.ssgproject.content_rule_ensure_pam_wheel_group_empty
- xccdf_org.ssgproject.content_rule_use_pam_wheel_group_for_su
Fixes: [SMI-200](https://scylladb.atlassian.net/browse/SMI-200)
Related https://github.com/scylladb/scylla-pkg/issues/2953
[SMI-200]: https://scylladb.atlassian.net/browse/SMI-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CIS compliance: Restrict Root Logins

---

packer/apply_cis_rules

To specify password maximum age for new accounts, edit the file /etc/login.defs and add or correct the following line:
PASS_MAX_DAYS 365
A value of 180 days is sufficient for many environments. The DoD requirement is 60. The profile requirement is 365.
Rationale:
Any password, no matter how complex, can eventually be cracked. Therefore, passwords need to be changed periodically. If the operating system does not limit the lifetime of passwords and force users to change their passwords, there is the risk that the operating system passwords could be compromised.
Setting the password maximum age ensures users are required to periodically change their passwords. Requiring shorter password lifetimes increases the risk of users writing down the password in a convenient location subject to …

Set Password Maximum Age

---

packer/apply_cis_rules

To specify the number of days after a password expires (which signifies inactivity) until an account is permanently disabled, add or correct the following line in /etc/default/useradd:
```
INACTIVE=45
```
If a password is currently on the verge of expiration, then 45 day(s) remain(s) until the account is automatically disabled. However, if the password will not expire for another 60 days, then 60 days plus 45 day(s) could elapse until the account would be automatically disabled. See the useradd man page for more information.
Rationale:
Inactive identifiers pose a risk to systems and applications because attackers may exploit an inactive identifier and potentially obtain undetected access to the system. Disabling inactive accounts ensures that accounts which may not have been responsibly …

Set Account Expiration Following Inactivity
